JoshuaKGoldberg/create-typescript-app

.github/workflows/compliance.yml
Amusing that https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/13 was closed automatically.
=> chore: don't auto-close noncompliant PRs

.markdownlint.json, README.md
I tried to get the manually colored badges to be the same color as the GitHub badge. But, the build badge is not super useful IMO. Removed.
=> docs: more badges

.github/actions/prepare/action.yml, .github/workflows/lint.yml
Copies `prettier.yml` to a new `lint.yml` workflow that runs ESLint.
Also removes a duplicate `actions/checkout@v3` from the prepare script. I think it's not needed?
=> chore: add lint.yml to run ESLint in CI

.ts-prunerc, package.json, src/types.ts, yarn.lock
Adds a `lint:prune` command that runs `ts-prune`.
=> chore: add ts-prune to CI

package.json, src/greet.ts, src/index.ts
`main` is needed to be `import`ed / `require`d: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#main
...and `---/types` does not exist, just `---/types.js`.
=> fix: corrected .js and main imports for Node importing

.eslintrc.cjs
Moves TypeScript interface & type key sorting in ESLint to an override scope so that it only applies to TypeScript files.
=> chore: move "plugin:typescript-sort-keys/recommended" to override scope

.github/workflows/test.yml, .gitignore, .npmignore, .ts-prunerc, cspell.json, package.json, pnpm-lock.yaml, vitest.config.ts
Adds `--coverage` to testing in CI, with coverage configured to output both `html` and `lcov`.
=> chore: add test coverage testing with Codecov

README.md, cspell.json
Quick lil docs touchup for code coverage in the README.md. Rewords a couple of existing badges so the images all fit on one line in the common GitHub Markdown preview width.
=> docs: add codecov badge

.github/DEVELOPMENT.md
Explains each of the tools, including how to run each of them.
Only Prettier is missing the `pnpm` command - since it gets done for folks automatically.
=> docs: filled out DEVELOPMENT.md

.eslintrc.cjs, tsconfig.eslint.json
Two fixes:
* Adds & uses a `tsconfig.eslint.json` that includes all files, not just those under `src`
* Moves `parserOptions.project` and the typed `deprecation/deprecation` rule to just TypeScript source files, not JS
=> fix: properly separated typed and untyped linting

package.json, pnpm-lock.yaml, vitest.config.ts
Switches the test coverage provider from `c8` to `istanbul`.
=> chore: fix coverage computation to ignore types

.releaserc.json
In lieu of https://github.com/semantic-release/git/issues/280 being fixed.
I still want `package.json` to be committed whenever a new version is published, just not ... any other assets.
=> chore: set assets to [], not false

.releaserc.json
Does what the issue describes: includes `package.json` as a committed file.
=> chore: include package.json in semantic-release/git

.github/workflows/release.yml, .releaserc.json, CHANGELOG.md, cspell.json, package.json, pnpm-lock.yaml
Pending https://github.com/semantic-release/changelog/issues/279 having a resolution, this uses a manual script to swap out `\n# ` for `\n## ` in `CHANGELOG.md`.
=> feat: used semantic-release/exec to clean changelog headings

.github/workflows/release.yml
Uses https://github.com/marketplace/actions/branch-protection-bot to temporarily disable the default branch's branch protections just when running `release-it`.
=> fix: temporarily disable branch protections for release-it

.eslintignore
As the issue describes, adds `coverage` to the ignored directories list.
=> chore: ignore coverage/ directory for linting

script/setup.js
Goes by the zx docs saying you don't need to explicitly `"` escape out inputs. https://github.com/google/zx#command-
=> fix: corrected description quote in setup script

script/setup.js
Turns out the file path that's being imported is `.allcontributorsrc`, not `.allcontributorsrc.json`. ES Module JSON imports don't support importing files that don't have the `.json` extension. 🤷 
So this switches to using `JSON.parse` and `fs.readFile`.
=> fix: corrected allcontributors setup import path with fs

CHANGELOG.md, script/setup.js
Applies two more things in the setup script:
* Runs `git tag -d $(git tag -l)` to delete _local_ Git tags (they can be retrieved again with `git fetch`
* Resets `CHANGELOG.md` to just `# Changelog`
=> feat: clear CHANGELOG.md and local Git tags in setup

.release-it.json, CHANGELOG.md
Adjusts the existing `CHANGELOG.md` to correct some `###`s, and sets `# Changelog` as the header in the release-it settings.
=> feat: add header to CHANGELOG.md

README.md, script/setup.js
Uses `fs.appendFile` instead of the more nuanced `replace-in-file` approach.
=> fix: only append README.md notice once in setup

.github/workflows/packages.yml, package.json, pnpm-lock.yaml, script/setup.js
Uses Octokit to call GitHub's REST API for populating repository settings. Gets everything in the issue except for _ Limit how many branches and tags can be updated in a single push_ because I can't find an API to do that. 🤷 
Also changes how devDependency packages work for setup. Previously the setup script would install & uninstall them as needed. Now they come installed in the repo, and get uninstalled at the end of the setup script. This way running setup doesn't take as long to start - and they're properly versioned.
=> feat: use Octokit to populate more settings

.github/renovate.json
Removes the erroneous `matchUpdateTypes`. Let's just automerge everything!
IIRC I'd long ago gotten a message somewhere about `matchUpdateTypes` being necessary. 🤷
=> fix: correct renovate config

.github/workflows/release.yml, script/setup.js
Gives up on using nice pre-made solutions. Instead copy & pastes the existing script from `setup/script.js`. 🤷
=> feat: re-add branch protection toggling in release.yml

.github/workflows/setup.yml, package.json, script/setup-test-e2e.js, script/setup.js, script/setup.test.js
Adds a rudimentary end-to-end test to the setup script. It also gets removed on setup.
In theory this could also test other parts of setup: that the name in files is replaced, that the setup script is removed, etc. But I opted not to for now.
=> chore: end-to-end test setup script

.github/workflows/release.yml, .npmignore, vitest.config.ts
This PR adds in a build step to the `release.yml` so the build artefacts exist for publishing. It also excludes `src` from publishing as it bloats package size and isn't used.
PR requested here: https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/147#issuecomment-1364555919
It also ensure vitest doesn't try and run tests in the `lib` folder.
=> fix: run build prior to release

.github/PULL_REQUEST_TEMPLATE.md, script/labels.json
Updates the PR template and setup script `labels.json`
=> feat: added 'status: ' prefix to 'accepting prs' and 'wontfix' labels

.eslintrc.cjs, package.json, pnpm-lock.yaml
Enables the lint rule. It has no violations in code on `main` right now, but I verified that removing the `.js` from an import did cause a complaint from the rule.
=> chore: enable import/extensions ESLint rule

.eslintrc.cjs
Changed the override files in .eslintrc.cjs to include both ".json" and ".jsonc" files and checked for any lint issues.
=> fix: include .jsonc files in the override files

.github/workflows/compliance.yml
Add `allcontributors` to `ignore-authors` in compliance job for pull requests
=> ci: add allcontributors to ignore-authors

.github/workflows/post-release.yml
Used https://github.com/apexskier/github-release-commenter action to add comments about release to related PRs and issues.
Functionality mentioned in the linked issue comes from `semantic-release` https://github.com/h6s-dev/h6s/blob/80f12bf7c7f75d974aadb39a9b6823c5d589513c/.releaserc.json#L16 
I saw it was replaced by `release-it` in this repo so we needed another solution.
Working example:
[Workflow file](https://github.com/winglang/wing/blob/e7551dcda97eab78aa17a9bc08385ff78d8503fe/.github/workflows/release-commenter.yml#L13)
[PR comment](https://github.com/winglang/wing/pull/1540#issuecomment-1431398410)
[Issue comment](https://github.com/winglang/wing/issues/1390#issuecomment-1412924184)
=> chore: comment on prs and issues with release info

.all-contributorsrc
Enable the `all-contibutors` rule to sort contributors alphabetically.
=> chore: enable contributors sort alphabetically rule in .all-contributorsrc

script/setup.js
Add `chalk` to `pnpm remove` at the end of setup so that it is installed after running setup.
=> fix: remove chalk dependency after pnpm setup

README.md, script/setup.js
* Removes the redundant notice about being a template repo from the bottom of the README (it gets populated by the setup script)
* Switches single replacement strings to global replacement regexps in the setup script
=> fix: replace all instances of old strings in setup script

.eslintrc.cjs, package.json, pnpm-lock.yaml
This was extracted from https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/285#pullrequestreview-1334988725
- Added type hints for eslint config, this adds proper intellisense inside editors
=> chore: add type hints for eslint config

package.json, pnpm-lock.yaml, script/setup.js
Calls to `git remote -v` to get the repo URL, and parses that as `--owner` and `--repository` field defaults.
Note that this doesn't add `--description` as a default because I don't want to mess with calling to the GitHub API & potentially needing to authenticate. If someone really wants to add that in I'd encourage them to file a separate feature request issue. 🙂
=> feat: default owner and repository to Git origin

script/labels.json
added the following code to labels.json:
```
{
"color": "#05104F",
"description": "Not yet ready for implementation or a pull request",
"name": "status: in discussion"
},
```
=> chore: add in discussion label

script/setup.js
Adds ```--skip-uninstalls``` option, ```skipUninstalls``` constant, skips removal of ```/script``` and,  skips uninstallation of devDependencies only used in setup.
```
if (skipUninstalls) {
console.log();
console.log(chalk.gray`➖ Skipping removal of setup script.`);
console.log(
chalk.gray`➖ Skipping removal of devDependencies only used for setup.`
);
} else {
await withSpinner(
async () => {
await fs.rm("./script", { force: true, recursive: true });
await fs.rm(".github/workflows/setup.yml");
},
{
startText: `Removing setup script...`,
successText: `Removed setup script.`,
stopText: `Error removing setup script.`,
errorText: `Could not remove setup script. `,
}
);
await withSpinner(
async () => {
await $`pnpm remove execa @clack/prompts all-contributors-cli chalk octokit npm-user …
```
=> chore: Add --skip-uninstalls option to setup script

vitest.config.ts
https://vitest.dev/config/#exclude
=> chore: exclude lib/ in vitest

.github/DEVELOPMENT.md, README.md, package.json, pnpm-lock.yaml, src/greet.test.ts, src/greet.ts, vitest.config.ts
Brings in [console-fail-test](https://github.com/JoshuaKGoldberg/console-fail-test) and mentions it alongside other testing docs.
Refactors `greet` just a bit to rebind `console.log` each time the function is called. That way it doesn't mess with `console.log` before console-fail-test does.
=> chore: add console-fail-test to tests

.vscode/settings.json
Added `"editor.rulers": [80]` to `.vscode/settings.json`.
This should add a ruler to indicate when a line break will occur.
=> chore: add rulers to vscode settings

script/setup-test-e2e.js, script/setup.js
I added some logic to add the running user to the `all-contributors` list (according to the authenticated GitHub CLI account).
At first, I tried only to use the owner variable that the user prompted, but it failed the tests, where a fabricated owner name was provided; if you prefer to only use the provided owner name without reaching out to gh CLI, we might need to adjust the tests a little bit.
=> feat: add running user to all-contributors

.eslintrc.cjs, script/setup.js
Uses a `while (true)` to continuously check if the `repository` exists. If it doesn't, the user can either:
* Bail out (`"bail"`)
* Create a new repository (`"create"`)
* Try again with a different repository (`"different"`)
Moves the `octokit` creation logic up in the file so that it can be used for repository checking. This is necessary because the `owner` might be private organization/user.
=> feat: offer to create or use a different repository in setup

.eslintrc.cjs, script/setup.js
Adds a nice and friendly notice on top of the ESLint config, with links to a couple of core docs.
Also removes that notice in the setup script - I figure consuming repos likely don't want my notices.
=> docs: added friendly explainer on top of ESLint config

script/setup.js
After hydrating allowed labels, any remaining (not allowed) existing label is deleted with [`gh label delete`](https://cli.github.com/manual/gh_label_delete).
=> feat: delete unnecessary labels on setup

script/setup.js
Uses a `try`/`catch` with a manual `console.error`. Because this is really part of the script setup, directly calls `process.exit(0)` instead of throwing an error through the normal handling.
=> feat: improve complaint when gh auth status fails

.github/workflows/release.yml, .release-it.json, README.md
Per https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/390#issuecomment-1543335037, the workflow needs to be manually fired.
Also removes an old unnecessary `hooks:bump` line from `.release-it.json` that I don't think ever did anything.
=> fix: manually call post-release.yml on release

.github/workflows/post-release.yml
Uses `npm pkg get version` to set the npm version in an `npm_version` env variable per https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable. Then uses it in the comment template.
=> fix: use npm pkg version in post-release

.eslintrc.cjs, script/setup.js
Runs `--fix` to fix up violations.
=> build: enabled ESLint curly rule

.github/workflows/post-release.yml
* `package.json` wasn't being found because the repo wasn't checked out yet
* `release_link` is a full Markdown link, not the direct URL
=> fix: fix post-release.yml comment-template links

.github/workflows/post-release.yml
=> fix: remove quotes and curly from post-release npm version link

.eslintrc.cjs, script/setup.js
=> feat: add caughtErrors to no-unused-vars

.github/workflows/setup.yml, script/setup-test-e2e.js, src/hydrate/values/hydrationInputValues.test.ts, src/setup/setupWithInformation.ts, src/shared/inputs.ts
Uses similar tracking to the hydration script.
=> build: add coverage tracking to setup script

cspell.json
Switches to a relative path so that it doesn't detect paths like `src/coverage` by accident, if they happen to exist.
=> fix: ignore all root coverage directories in spelling

src/hydrate/steps/clearUnnecessaryFiles.ts, src/hydrate/steps/writing/creation/index.ts, src/hydrate/steps/writing/creation/rootFiles.ts, src/hydrate/steps/writing/creation/writePackageJson.test.ts, src/hydrate/steps/writing/creation/writePackageJson.ts, src/hydrate/steps/writing/writeStructure.ts, src/setup/settings/addOwnerAsAllContributor.ts, src/setup/steps/labels/hydrateRepositoryLabels.ts, src/setup/steps/updateLocalFiles.ts, src/shared/readFileAsJson.test.ts, src/shared/readFileAsJson.ts
Splits the creation of new `package.json` contents into a new `writePackageJson` file. It reads the existing `package.json` as JSON and uses all previously existing fields by default.
Note that this PR also standardizes from `JSON` to `Json` in file names.
=> fix: respect existing package.json contents in hydration

cspell.json, src/hydrate/steps/clearUnnecessaryFiles.test.ts, src/hydrate/steps/clearUnnecessaryFiles.ts
Adds some more globs to the list of those to remove.
=> feat: remove more common unnecessary files

src/hydrate/hydrate.ts, src/hydrate/steps/runCommand.test.ts, src/hydrate/steps/runCommand.ts, src/shared/cli/spinners.ts, src/shared/defaults.ts
Per the issue, runs `pnpm lint --fix` near the end of hydration. Also runs `pnpm format --write`. For both, if there was an error, the user is warned to run the command themselves.
Rewords from _"Succeeded"_ to _"Passed"_ for spinner blocks to indicate that there might not have been a total success.
=> feat: run ESLint and Prettier fixers in hydration

src/setup/settings/addOwnerAsAllContributor.ts, src/setup/steps/labels/getExistingEquivalentLabel.test.ts, src/setup/steps/labels/getExistingEquivalentLabel.ts
Fixes the `.find` logic to match on an aliased or prefixed label.
=> fix: match existing, prefixed labels in setup

src/setup/steps/hydrateRepositorySettings.ts
Adds the two settings for the GitHub API per https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository.
=> fix: specify squash merge defaults in repo setup

.github/workflows/post-release.yml, .github/workflows/release.yml
Removes the manual dispatch of `post-release.yml`, so that `release.types` > `- published` is how it's triggered.
Co-authored-by: Navin Moorthy <navin007.a@gmail.com>
=> fix: only run post-release once

.eslintrc.cjs, package.json, sample.js, src/hydrate/steps/writing/creation/rootFiles.ts, src/hydrate/steps/writing/creation/writePackageJson.ts
Changes the `pnpm run lint` command to explicitly include dotfiles. I don't like making the command more complex, but I couldn't figure out a way to get it to include dotfiles... fortunately, once [ESLint flat config](https://eslint.org/docs/latest/use/configure/configuration-files-new) is usable, we can switch to that and remove the change to the `lint` script.
Filed https://github.com/azat-io/eslint-plugin-perfectionist/issues/22 as part of this.
=> fix: lint .eslintrc.cjs

.eslintrc.cjs, package.json, pnpm-lock.yaml
Uses the option directly, so we can remove the disable comments in the config. Yay!
=> feat: use eslint-plugin-perfection's partition-by-comment

package.json, pnpm-lock.yaml, src/setup/steps/uninstallPackages.ts
Since it's used in hydration, it should be installed.
=> fix: made @clack/prompts a full dependency

src/hydrate/steps/writing/creation/writePackageJson.test.ts, src/hydrate/steps/writing/creation/writePackageJson.ts
Adds a little utility to remove any not-allowed ones.
=> feat: remove known unnecessary devDependencies

src/setup/steps/uninstallPackages.ts
`prettier` needs to be demoted from a `dependency` to a `devDependency`. Right now it's just removed altogether.
=> fix: put prettier back as a devDependency in setup

src/setup/steps/updateLocalFiles.ts
Adds a couple of removals and clumps them together.
=> fix: remove hydrate entries from package.json in setup

src/setup/steps/hydrateRepositorySettings.ts
Per https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository, enables all three options in the API.
=> feat: add security_and_analysis enablement to setup

src/setup/steps/labels/outcomeLabels.ts
=> feat: Add type:cleanup to outcomeLabels

src/setup/steps/hydrateRepositorySettings.ts
Removing it fixes the 422 complaint for public repos.
I guess this would be useful for private repos, but that logic doesn't exist in this template.
=> fix: don't enable GitHub's advanced_security

src/setup/setupWithInformation.ts, src/setup/steps/removeSetupScripts.ts, src/setup/steps/updateLocalFiles.ts
Removes a few more bits of setup info. Also fixes a string in the script.
=> fix: remove last hydrate/setup vestiges in setup

.eslintrc.cjs
=> feat: add logical-assignment-operators and operator-assignment lint rules

src/hydrate/index.ts, src/hydrate/steps/finalizeDependencies.ts, src/setup/steps/updateAllContributorsTable.ts
I think it's fine to run the command both in hydration and setup. It's not slow.
=> fix: also run npx all-contributors-cli generate in setup

src/hydrate/steps/writing/creation/writePackageJson.test.ts, src/hydrate/steps/writing/creation/writePackageJson.ts, src/shared/ensureGitRepository.test.ts, src/shared/ensureGitRepository.ts, src/shared/getDefaultSettings.ts, src/shared/runOrRestore.test.ts, src/shared/runOrRestore.ts
Changes split out of #668:
* If `git status` fails, runs `git init` to make the directory a repo
* Allows `package.json` to be empty, defaulting its contents to `{}`
=> feat: allowed hydration directory to be empty

src/shared/runOrRestore.ts
Adds the warning as described in the issue.
=> feat: added warning to CLIs

src/initialize/steps/updateLocalFiles.test.ts, src/initialize/steps/updateLocalFiles.ts
=> feat: allow blank package.json in readFileSafeAsJson

src/initialize/settings/addOwnerAsAllContributor.test.ts, src/initialize/settings/addOwnerAsAllContributor.ts, src/shared/types.ts
Adds some nice test coverage too.
=> feat: ensure running user is included in .all-contributorsrc

src/steps/updateLocalFiles.test.ts, src/steps/updateLocalFiles.ts
Yet another case where a non-existent (or empty) `package.json` caused issues.
=> fix: allow package.json to be empty in updateLocalFiles

src/steps/labels/getExistingEquivalentLabel.ts, src/steps/labels/initializeRepositoryLabels.test.ts, src/steps/labels/initializeRepositoryLabels.ts
Also checks for outcome labels whose stripped version (no prefix) matches the existing label.
=> fix: respect stripped versions of outcome labels

docs/InitializationFromTemplate.md, docs/InitializationFromTerminal.md, src/bin/index.ts, src/create/createWithValues.ts, src/create/index.ts, src/initialize/initializeWithValues.ts, src/shared/args.ts, src/shared/augmentValuesWithNpmInfo.ts, src/shared/doesRepositoryExist.test.ts, src/shared/doesRepositoryExist.ts, src/shared/ensureRepositoryExists.test.ts, src/shared/ensureRepositoryExists.ts, src/shared/inputs.ts, src/steps/initializeRepositorySettings.ts, src/steps/writeReadme.test.ts
Streamlines the heck out of the `--mode create` (`npx template-typescript-node-package`) experience:
* Instead of telling you to run some initialize commands, it offers to run them for you
* Similarly, after creating a new repository, the creation script will offer to update the repo using GitHub's APIs for you
* Adds a `--create-repository` flag to automatically do those things
=> feat: automate repository creation for --mode create

src/steps/writing/creation/dotGitHub/createWorkflowFile.ts, src/steps/writing/creation/dotGitHub/workflows.ts
It was included in the original PR but I'd never added it to the template.
=> fix: add missing id-token permissions to release.yml template

knip.jsonc, src/steps/writing/writeStructure.ts
Applies the suggested fix from https://github.com/typicode/husky/issues/1177 of manually changing the file's mode with `chmod`.
=> fix: chmod ug+x .husky/pre-commit after writing structure

src/create/createRerunSuggestion.test.ts, src/create/createRerunSuggestion.ts, src/create/index.ts, src/shared/options/augmentOptionsWithExcludes.test.ts, src/shared/options/readOptions.ts, src/shared/types.ts, src/steps/finalizeDependencies.test.ts, src/steps/updateLocalFiles.test.ts, src/steps/writeReadme.test.ts, src/steps/writing/creation/writePackageJson.test.ts
Instead of `pnpm initialize`, adds a re-run suggestion that takes in the parsed options and re-prints them in the CLI. It hardcodes `skip-github-api` and `skip-install` to `false` because they're needed for the new repo.
=> fix: suggest a re-run command instead of pnpm initialize after offline creation

src/steps/initializeGitHubRepository/index.ts, src/steps/initializeGitRemote.test.ts, src/steps/initializeGitRemote.ts
In `initializeGitHubRepository`, if there isn't yet an `origin` remote per `git remote`, adds one.
=> fix: initialize git remote if needed

src/shared/packages.test.ts, src/shared/packages.ts, src/steps/finalizeDependencies.test.ts, src/steps/finalizeDependencies.ts, src/steps/uninstallPackages.ts
Refactors the two existing package removal functions to be just one.
=> fix: don't pnpm remove an empty list of packages

.eslintrc.cjs, package.json, src/steps/writing/creation/createESLintRC.ts
I don't know this is intended, but generally forks include me preferred set in config file rather than cli options.
thanks take a look the PR!
=> feat: move `--report-unused-disable-directives` cli option to `.eslintrc.cjs`

src/steps/initializeGitHubRepository/labels/getExistingEquivalentLabel.test.ts, src/steps/initializeGitHubRepository/labels/getExistingEquivalentLabel.ts, src/steps/initializeGitHubRepository/labels/initializeRepositoryLabels.test.ts, src/steps/initializeGitHubRepository/labels/initializeRepositoryLabels.ts
Removes `gh label delete` because if a label already exists, we're always either...
* ...editing it to be the equivalent outcome label
* ...leaving it be because it's an unrelated repo-specific label
While I'm here, applies a quick optimization to only send edit requests for existing labels whose info is different from their equivalent outcome.
=> fix: allow existing labels (never gh label delete)

.github/CONTRIBUTING.md
Continues the chain of https://github.com/microsoft/TypeScript/blob/a6df6c04d5dd16ecb031aba0d7499f6e9be940b6/CONTRIBUTING.md#issue-claiming -> https://github.com/typescript-eslint/typescript-eslint/pull/7356.
=> docs: mentioned lack of issue claiming

src/steps/writeReadme.test.ts, src/steps/writeReadme.ts, src/steps/writing/creation/writePackageJson.test.ts
Joins with `"\n"` instead of `""`.
=> fix: place newlines between README.md badges

package.json, pnpm-lock.yaml, src/shared/options/getPrefillOrPromptedOption.test.ts, src/shared/options/getPrefillOrPromptedOption.ts, src/shared/options/readGitAndNpmDefaults/index.ts, src/shared/options/readOptions.ts, src/shared/tryCatchLazyValueAsync.test.ts, src/shared/tryCatchLazyValueAsync.ts, src/steps/uninstallPackages.ts
Wraps all the defaults in `lazy-value` to lazily evaluate them.
The `getGitAndNpmDefaults` function itself is pretty complex so I'm still not unit testing it. Ah well.
=> feat: run getGitAndNpmDefaults lazily

src/create/createWithOptions.ts, src/initialize/initializeWithOptions.ts, src/migrate/migrateWithOptions.ts, src/shared/options/ensureRepositoryExists.test.ts, src/shared/options/ensureRepositoryExists.ts, src/shared/options/getGitHub.test.ts, src/shared/options/getGitHub.ts, src/shared/options/readOptions.ts, src/steps/detectExistingContributors.test.ts, src/steps/detectExistingContributors.ts
Wraps the existing `octokit` property in one that also has `auth`.
=> feat: reuse GitHub auth in all-contributors-cli

.all-contributorsrc, .prettierignore, src/steps/writing/creation/rootFiles.ts
This PR is a fix for the all-contributors/cli#347 issue now being resolved. Ignoring the `.all-contributorsrc` file in the `.prettierignore` file is unnecessary. 😎
=> fix: remove .all-contributorsrc from .prettierignore

src/steps/writing/creation/writePackageJson.ts
updated devDependenciesToRemove array with eslint-plugin-jest and ts-jest
=> feat: uninstall eslint-plugin-jest and ts-jest as dev dependencies

.github/workflows/lint-packages.yml, src/steps/writing/creation/dotGitHub/createWorkflowFile.test.ts, src/steps/writing/creation/dotGitHub/createWorkflowFile.ts, src/steps/writing/creation/dotGitHub/workflows.ts
Turns out it was failing over diffs like:
```plaintext
diff --git a/.github/workflows/tsc.yml b/.github/workflows/tsc.yml
index 3b20f24..0e11a07 100644
--- a/.github/workflows/tsc.yml
+++ b/.github/workflows/tsc.yml
@@ -2,7 +2,7 @@ jobs:
type_check:
runs-on: ubuntu-latest
steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v3
- uses: ./.github/actions/prepare
- run: pnpm tsc
```
You can see them by downloading the raw logs artifacts from the failing builds.
=> fix: update remaining actions/checkout versions from 3 to 4

src/steps/writing/creation/dotGitHub/workflows.ts
Turns out it'd been using the wrong excludes key.
=> fix: correct key for excluding lint-packages.yml

src/create/createWithOptions.ts, src/migrate/migrateWithOptions.ts, src/steps/writing/creation/index.ts, src/steps/writing/writeStructure.ts
Passes in the root `mode` to `writeStructure` -> `createStructure` so it knows not to call `createSrc` during migration.
=> fix: don't create src/ files during --mode migrate

src/steps/updateLocalFiles.test.ts, src/steps/updateLocalFiles.ts
Adds a manual find-and-replace back in `updateLocalFiles`.
=> fix: undo overwriting of README.md attribution in updateLocalFiles

src/steps/updateReadme.test.ts, src/steps/updateReadme.ts
Uses the `` line as a detector to know whether to append.
Note that _creation_ was fixed previously, just not _appending_ (updating).
=> fix: only append README.md notice if it doesn't yet exist

src/initialize/initializeWithOptions.ts, src/steps/updateLocalFiles.test.ts, src/steps/updateLocalFiles.ts
Added additional config parameter to `updateLocalFiles`, so we can skip overwriting package version inside migrate script.
=> fix: preserve package version during migration

.github/DEVELOPMENT.md, README.md, docs/FAQs.md, src/shared/options/augmentOptionsWithExcludes.test.ts, src/shared/options/augmentOptionsWithExcludes.ts, src/shared/options/readOptions.ts, src/shared/types.ts
Describes the new "common" base as what I imagine most repositories would want, and gives it the `hint: "recommended"` instead of the "everything" base. And adds some more test coverage to `augmentOptionsWithExcludes`.
I think Knip might technically belong in the "everything" base per the current descriptions... but gosh darn is it so useful. I wonder what's better: including it in "common" so everyone gets the benefit? Or pushing it to "everything" so as a reward for trying that one out? For now I think the former is more likely to be beneficial.
```plaintext
│
◆  How much tooling would you like the template to set up for you?
│  ○ everything  The most comprehensive tooling imaginable: sorting, spellchecking, and more!
│  ● essentials  Bare starters plus testing and automation for …
```
=> feat: added a 'common' config base, with more docs

src/initialize/initializeWithOptions.ts, src/migrate/migrateWithOptions.ts, src/steps/updateLocalFiles.test.ts, src/steps/updateLocalFiles.ts
This is now the second piece of conditional logic in `updateLocalFiles`, so I switched its config parameter to directly take in `mode: Mode`.
This particular change also finally got its snapshot tests past my personal _"tl;dr"_ threshold. I switched the logic based on `logic` to use more targeted `toHaveBeenCalledWith`s instead.
=> fix: don't remove package.json bin in migration

src/shared/cli/startLineWithDots.ts
Switches from `setInterval` to `setTimeout` so if one crashes, new timers won't continue to be created.
Also removes a duplicate `dots += 1`.
=> fix: use setTimeout, not setInterval

.github/CODE_OF_CONDUCT.md, .github/SECURITY.md, docs/Options.md, script/migrate-test-e2e.js, src/bin/index.test.ts, src/bin/index.ts, src/bin/mode.ts, src/create/createRerunSuggestion.test.ts, src/create/createRerunSuggestion.ts, src/create/index.ts, src/initialize/index.ts, src/migrate/index.ts, src/shared/options/args.ts, src/shared/options/augmentOptionsWithExcludes.test.ts, src/shared/options/detectEmailRedundancy.test.ts, src/shared/options/detectEmailRedundancy.ts, src/shared/options/optionsSchema.ts, src/shared/options/readOptionDefaults/index.test.ts, src/shared/options/readOptionDefaults/index.ts, src/shared/options/readOptions.test.ts, src/shared/options/readOptions.ts, src/shared/types.ts, src/steps/finalizeDependencies.test.ts, src/steps/updateLocalFiles.test.ts, src/steps/writeReadme/generateTopContent.test.ts, src/steps/writeReadme/index.test.ts, src/steps/writing/creation/dotGitHub/createDevelopment.test.ts, src/steps/writing/creation/dotGitHub/createDotGitHubFiles.ts, src/steps/writing/creation/writePackageJson.test.ts, src/steps/writing/creation/writePackageJson.ts
Builds off the ideas in #851 by adding optional `--email-github` and `--email-npm` overrides. Adds a string complaint if an improper combination is specified: one of those two without the other or `email`, or both of those two along with `email`. At this point `email` is now a required option.
Adjusts the sorting of rerun suggestions a bit to make sure emails are sorted inline and `--base` comes immediately after `--mode`.
Also fills in some unit test coverage in the area.
=> feat: allow specific GitHub and/or npm emails

src/steps/updateLocalFiles.test.ts, src/steps/updateLocalFiles.ts
Applies two tangentially related fixes:
* The original description can be replaced with a plain string - it doesn't need a regular expression
* The rerun suggestion for descriptions should escape `$`s
=> fix: replace existing description with string, not regex

.github/workflows/release.yml, src/steps/writing/creation/dotGitHub/createWorkflowFile.ts, src/steps/writing/creation/dotGitHub/workflows.ts
Switches `actions/checkout@4` to fetch from `ref: main` (the branch) instead of the commit that triggered the workflow. Doing so should mean that every release workflow runs on the latest commit as of when it _starts_.
This should mean that if N release-worthy commits occur quickly:
1. The first one should always finish releasing nicely
2. The remaining 1...N commits will each 
I don't love that this solution results in 1...N release workflows each deleting branch protection, doing nothing, then recreating the branch protection. But given https://github.com/orgs/community/discussions/12835 I don't see a way around it. The branch protection shenanigans should be made better by #145.
=> fix: remove cancel-in-progress from release.yml

src/steps/writing/creation/writePackageJson.ts
Added package `@vitest/coverage-istanbul` to devDependenciestoRemove as requested in #759
=> feat: Add @vitest/coverage-istanbul to devDependenciesToRemove

.github/renovate.json, src/steps/writing/creation/dotGitHub/createDotGitHubFiles.ts
Updates the repo's `.github/renovate.json` and backing template.
=> chore: use Renovate's minimumReleaseAge

.github/DEVELOPMENT.md, package.json, src/steps/writing/creation/dotGitHub/createDevelopment.test.ts, src/steps/writing/creation/dotGitHub/createDevelopment.ts, src/steps/writing/creation/writePackageJson.test.ts, src/steps/writing/creation/writePackageJson.ts
Does the swap, both in code and docs.
=> feat: switch format:write to format --write

src/steps/finalizeDependencies.test.ts, src/steps/finalizeDependencies.ts
Adds with `execaCommand` since it's already being used.
=> feat: run npm dedupe at end of finalizeDependencies

.eslintrc.cjs, cspell.json, src/create/index.ts, src/initialize/index.ts, src/migrate/index.ts, src/shared/__snapshots__/generateNextSteps.test.ts.snap, src/shared/cli/outro.test.ts, src/shared/cli/outro.ts, src/shared/generateNextSteps.test.ts, src/shared/generateNextSteps.ts, src/shared/options/readOptionDefaults/index.ts, src/steps/writing/creation/createESLintRC.test.ts, src/steps/writing/creation/createESLintRC.ts
Pulls the logging of next steps (app(s) and/or token(s) to enable) into a dedicated `generateNextSteps` function, with unit tests. `outro` now allows a `variant` for each group, as this new logging isn't the preivously-always-gray code-style logging.
=> fix: base suggested next steps on options

.github/CONTRIBUTING.md, src/steps/writing/creation/dotGitHub/createDotGitHubFiles.ts
Corrects searches and text for the label having previously switched from `accepting prs` to `status: accepting prs`, and adds `no:assignee` to the search.
=> docs: explicitly mention issues being unassigned in contributing guidelines

docs/Options.md, src/create/createRerunSuggestion.test.ts, src/create/createWithOptions.ts, src/shared/options/args.ts, src/shared/options/augmentOptionsWithExcludes.test.ts, src/shared/options/ensureRepositoryExists.test.ts, src/shared/options/ensureRepositoryExists.ts, src/shared/options/optionsSchema.ts, src/shared/options/readOptions.test.ts, src/shared/options/readOptions.ts, src/shared/types.ts, src/steps/finalizeDependencies.test.ts, src/steps/updateLocalFiles.test.ts, src/steps/writeReadme/generateTopContent.test.ts, src/steps/writeReadme/index.test.ts, src/steps/writing/creation/createESLintRC.test.ts, src/steps/writing/creation/dotGitHub/createDevelopment.test.ts, src/steps/writing/creation/writePackageJson.test.ts
=> feat: remove --create-repository option

src/steps/writing/creation/createESLintRC.test.ts, src/steps/writing/creation/createESLintRC.ts
Instead of hardcoding the one allowed module name to `create-typescript-app`, uses `options.repository`.
=> fix: use options.repository for n/no-missing-import's allowedModules

src/create/createWithOptions.ts, src/shared/options/ensureRepositoryExists.test.ts, src/shared/options/ensureRepositoryExists.ts, src/shared/options/readOptions.ts
I remember now why `--create-repository` existed: if `mode` is `create`, then we'll want to attempt creating a new repo by default. So this PR infers a `createRepository` again in `ensureRepositoryExists`.
=> fix: correct create-repository-by-default logic

.github/workflows/release.yml, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
Uses my new https://github.com/JoshuaKGoldberg/release-it-action that contains much of the same logic as the previous `release.yml` contents. I stuck with the "delete and recreate branch protections" approach because (a) it's worked well and (b) other approaches had other limitations. 
I can't be 100% sure this works in this repo until it lands on `main` and tries a few release flows. But I did test it in a separate repo and it worked well there.
=> feat: use release-it-action for release flow

README.md, src/steps/writing/creation/writeAllContributorsRC.ts
I realized the 🤝 emoji is already used for the code of conduct badge.
=> fix: set emoji for all-contributors badge to 👪

.github/DEVELOPMENT.md, script/migrate-test-e2e.js, src/steps/writing/creation/dotGitHub/createDevelopment.test.ts, src/steps/writing/creation/dotGitHub/createDevelopment.ts, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
Adds `pnpm build || true` before `pnpm lint` in the templated `lint.yml`. That's what this repo already does, so this essentially makes templated repos more like this one.
=> feat: always run build || exit 0 before lint in CI

docs/Options.md, script/initialize-test-e2e.js, src/shared/options/args.ts, src/shared/options/createRepositoryWithApi.test.ts, src/shared/options/createRepositoryWithApi.ts, src/shared/options/ensureRepositoryExists.test.ts, src/shared/options/ensureRepositoryExists.ts, src/shared/options/optionsSchema.ts, src/shared/options/readOptions.test.ts, src/shared/options/readOptions.ts, src/shared/types.ts, src/steps/updateReadme.test.ts, src/steps/updateReadme.ts, src/steps/writeReadme/index.test.ts, src/steps/writeReadme/index.ts
GitHub doesn't have a unified _"create a new blank repository"_ API. So unless the new `--preserve-generated-from` option is true, repo creation will check whether the authenticated user has the same login as the `--owner` option, then use either `createForAuthenticatedUser` or `createInOrg.
Slightly rephrases the end-of-README notice while I'm here to remove my username from it. And in doing so, expands the _"does the notice already exist?"_ logic to check previous variants.
=> feat: add opt-in --preserve-generated-from option

.eslintrc.cjs, src/shared/options/ensureRepositoryExists.ts, src/steps/writing/creation/createESLintRC.test.ts, src/steps/writing/creation/createESLintRC.ts
This PR adds the following rules to the ESLint config:
- [no-useless-rename](https://eslint.org/docs/latest/rules/no-useless-rename)
- [object-shorthand](https://eslint.org/docs/latest/rules/object-shorthand) 
The rules have also been added to the created `.eslintrc` files and the test has been updated. Lint errors have been solved.
=> feat(lint): add `no-useless-rename` and `object-shorthand`

src/create/createWithOptions.ts
Moved the "Cleaning up files" `runCommand` call inside of the preceding conditional to only run if packages were installed.
For some reason my terminal won't let me put in emojis, so I'll use <(-.-)>
=> feat: skip file cleanup if installation is skipped

cspell.json, docs/FAQs.md
I'm a little pleasantly surprised to remember that it's only two steps...!
=> docs: add CJS/ESM emit entry

src/shared/options/getBase.test.ts, src/shared/options/getBase.ts, src/shared/options/readOptions.test.ts, src/shared/options/readOptions.ts, src/shared/types.ts
Add a naive solution for checking the existing `package.json` during migration to infer the base.
🐸
=> feat: infer base from package json scripts during migration

.github/workflows/accessibility-alt-text-bot.yml, src/steps/writing/creation/dotGitHub/createWorkflowFile.ts, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
This PR fixes an error associated with the newly implemented `accessibility-alt-text-bot` which was introduced by writing `issue` instead of `issues`.
I also looked into the GH actions docs and noticed that `created` is not a possible option on issues and pull requests - replaced with `opened`.
=> fix: typo in a11y bot creation

.github/workflows/accessibility-alt-text-bot.yml, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
This PR is hopefully the last one in the series of getting the `accessibility-alt-text-bot` correct by removing the unnecessary `if` statement in the `yml` job
=> chore: remove unnecessary if in a11y-alt-bot

src/steps/updateLocalFiles.test.ts, src/steps/updateLocalFiles.ts
Brings in https://github.com/adamreisnz/replace-in-file/#allow-emptyinvalid-paths to avoid crashing.
=> fix: allow empty paths for updating local files

README.md
This PR removes the visual underlines on badge links in README.md, introduced by the recent GitHub changes (to render the underlines by default). The problem was that the `<link>` and `<img>` tags were on separate lines, thus creating unnecessary spaces in between. These spaces were rendering empty links with an underline. 💖
=> fix: remove visual underlines on badge links in README.md

docs/FAQs.md
Bumps down the heading level of the _"What tooling ..."_ heading so we can keep all h2s alphabetical.
=> docs: mention tabs in FAQs

src/steps/initializeGitHubRepository/labels/outcomeLabels.ts
Adds relevant emojis to most label descriptions.
=> feat: add emoji to label descriptions

.all-contributorsrc, README.md, src/steps/writeReadme/findExistingBadges.test.ts, src/steps/writeReadme/generateTopContent.test.ts, src/steps/writeReadme/generateTopContent.ts, src/steps/writeReadme/index.test.ts, src/steps/writing/creation/writeAllContributorsRC.ts
This PR ports README.md badge underlines fix (in #1030) to templates that generates the badges in README.md files and its associated test. 💖
=> feat: port README.md badge underlines fix to templates

src/steps/clearUnnecessaryFiles.ts
Added `.prettier.config.js`, `.prettier.config.mjs` and `.prettier.config.cjs` to `clearUnnecessaryFiles.ts` in order for those files to be removed.
=> feat: Add prettier.config to clearUnnecessaryFiles.ts

docs/Options.md, src/bin/help.test.ts, src/shared/options/args.ts, src/shared/options/createOptionDefaults/index.test.ts, src/shared/options/createOptionDefaults/index.ts, src/shared/options/optionsSchema.ts, src/shared/options/readOptions.test.ts, src/shared/options/readOptions.ts, src/shared/types.ts, src/steps/writing/creation/writePackageJson.ts
Adds the `--bin` option with auto-detection from existing `package.json` contents.
Doesn't do anything about investigating whether to adjust `pnpm build` before `pnpm lint` & similar. That can be a followup.
=> feat: add --bin option

src/bin/index.test.ts, src/bin/index.ts
I was browsing the list of issues labeled `good first issue` and saw that issue #704 had its attached PR closed. The version feature has basically already been implemented, but this just adds the flag to display the version.
🧢
=> feat: add -v flag to display version

script/initialize-test-e2e.js, src/initialize/initializeWithOptions.ts, src/steps/createJoshuaKGoldbergReplacement.test.ts, src/steps/createJoshuaKGoldbergReplacement.ts, src/steps/updateLocalFiles.test.ts, src/steps/updateLocalFiles.ts, src/steps/updateReadme.test.ts, src/steps/updateReadme.ts, src/steps/writeReadme/index.test.ts, src/steps/writing/creation/dotGitHub/createDotGitHubFiles.ts
Uses a [`to` callback](https://github.com/adamreisnz/replace-in-file/#using-callbacks-for-to) to determine whether to swap out owner to `options.owner` in `"JoshuaKGoldberg"` _(always)_ or `"JoshuaKGoldberg/..."` (if the `...` is `options.repository`).
Also fixes some existing edge cases around owner replacements:
* Syncs up the end-of-readme attribution notice so there's only one place it's written in the templates
* Uses `options.owner` and `options.repository` in `createDotGitHubFiles` instead of hardcoding `JoshuaKGoldberg/create-typescript-app`.
=> fix: improve migration owner replacements

src/shared/options/getPrefillOrPromptedOption.test.ts, src/shared/options/getPrefillOrPromptedOption.ts, src/shared/options/readOptions.ts
A default value being present for `getPrefillOrPromptedValue` doesn't mean it should be used. Only a _provided_ value does. This adds an explicit `provided?: string` to the function's options.
=> fix: prompt for values when auto is off, regardless of a default value

src/steps/writeReadme/generateTopContent.test.ts, src/steps/writeReadme/generateTopContent.ts, src/steps/writeReadme/index.test.ts
Replaces the hardcoded `create-typescript-app` name with `options.repository`. Also adds non-blank strings to unit tests so the snapshots will reflect this.
=> fix: use repository name in README.md npm package badge

.vscode/settings.json, src/steps/writing/creation/dotVSCode.ts
Updated source.fixAll.eslint to "explicit"
=> feat: Updated source.fixAll.eslint to explicit

.github/workflows/test-initialize.yml, .github/workflows/test-migrate.yml, script/initialize-test-e2e.js, script/migrate-test-e2e.js
Keeps them running on `./coverage`, then swaps that to `./coverage-*` later in the workflow.
Comparing the performance of the two end-to-end test types from `main` (c06c62c):
| Test         | Baseline | Update   | Δ                      |
| ------------ | -------- | -------- | ---------------------- |
| `initialize` | `1m 25s` | `1m 21s` | ~0% (near zero change) |
| `migrate`    | `2m 45s` | `30s`    | 81% faster             |
Seems like this mostly improves migration. I guess initialization didn't have this bottleneck as badlly, and still runs the initialize script twice.
=> chore: keep coverage directories in-place for test-initialize and test-migrate

.all-contributorsrc, README.md, script/__snapshots__/migrate-test-e2e.js.snap, src/steps/writing/creation/writeAllContributorsRC.ts
Corrects the emojis and indentation in the `badgeTemplate` property.
Also sets `commitType` manually per #1090 - leaving the issue open.
=> chore: match .all-contributorsrc to template

script/__snapshots__/migrate-test-e2e.js.snap, script/migrate-test-e2e.js
In the migration script, after running with `--mode migrate` but before running test assertions, modifies a couple of files on disk:
1. `.all-contributorsrc`: Formats with `JSON.stringify(..., null, 2)` as it seems All Contributors isn't able to use Prettier for it
2. `.github/DEVELOPMENT.md`: Adds back in the `## The Setup Scripts` heading, as it's not part of the default template
Also wraps the `test`s in `describe` and standardizes naming just a bit. I'm very nitpicky.
=> chore: transform noisy files in e2e migration test

.vscode/settings.json, script/__snapshots__/migrate-test-e2e.js.snap, script/migrate-test-e2e.js
Resets the all-contributors count in the snapshot too. So there's much less diff noise around it.
In doing so, indicates that the snapshot file _might_ be changed. ANd that's ok.
=> chore: more e2e migration snapshots filters: contributors and line numbers

src/create/createRerunSuggestion.test.ts, src/create/createRerunSuggestion.ts
This PR fixes an issue in the rerun suggestions, where `true` is unnecessarily being printed. This change leads to the following:
```shell
npx create-typescript-app --mode create --skip-install true
npx create-typescript-app --mode create --skip-install
```
The related tests have also been changed.
=> fix: remove unnecessary boolean values in rerun suggestions

package.json, script/__snapshots__/migrate-test-e2e.js.snap, src/steps/writing/creation/writePackageJson.test.ts, src/steps/writing/creation/writePackageJson.ts
Includes a `files` entry if `bin` exists. Also strips a preceding `./` from it if it's there.
=> fix: include bin entry in package.json files

script/__snapshots__/migrate-test-e2e.js.snap, script/migrate-test-e2e.js
Fills in that little `\n` to get rid of the file's expected diffs.
=> chore: fill in newline for .github/DEVELOPMENT.md migration snapshot

.github/workflows/lint-knip.yml, script/__snapshots__/migrate-test-e2e.js.snap, script/migrate-test-e2e.js, src/create/createWithOptions.ts, src/initialize/initializeWithOptions.ts, src/migrate/migrateWithOptions.ts, src/shared/createCleanUpFilesCommands.test.ts, src/shared/createCleanUpFilesCommands.ts, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
Finally makes it so a `pnpm build || exit 0` only happens if `bin` is specified. This is because:
* `n/no-missing-import` will complain if the referenced `.js` file doesn't exist
* The only way for that file to exist is to `build`
* But, building failing -especially in migrating an existing repo- shouldn't prevent the rest of the commands from running
=> fix: normalize whether build happens before lint/knip

.all-contributorsrc, README.md, script/__snapshots__/migrate-test-e2e.js.snap, src/steps/writeReadme/findExistingBadges.test.ts, src/steps/writeReadme/findExistingBadges.ts, src/steps/writeReadme/generateTopContent.test.ts, src/steps/writeReadme/generateTopContent.ts, src/steps/writeReadme/index.test.ts, src/steps/writing/creation/writeAllContributorsRC.ts
Standardizes README.md badges to have the emoji at the start because I want them consistent and the npm version badge can't have the emoji tacked on.
Streamlines them by removing the _sponsor_ and _style_ badges and trimming the _code of conduct_ badge down to say _kept_ instead of _enforced. This means they should all fit on one line in the npm site.
Also fixes a bug in `findExistingBadges` where matchers were being re-created _then_ looped on, instead of re-created each instance of the loop. `/g` regexp state matters!
=> feat: streamlined and unified README.md badges

.all-contributorsrc, README.md, script/__snapshots__/migrate-test-e2e.js.snap, src/steps/writeReadme/generateTopContent.test.ts, src/steps/writeReadme/generateTopContent.ts, src/steps/writeReadme/index.test.ts, src/steps/writing/creation/writeAllContributorsRC.ts
For each README.md image badge, I:
1. Copied the image into Chrome's URL bar -> it stayed the same
2. Copied the url into VS Code -> it became encoded like this
🤷 maybe this won't trip the same GitHub-side bug seen in #1155?
=> fix: encode emojis in README.md badge images

src/shared/createCleanUpFilesCommands.test.ts, src/shared/createCleanUpFilesCommands.ts
Removes the `|| exit 0` per the issue.
=> fix: don't || exit 0 in cleanup build

knip.jsonc, script/__snapshots__/migrate-test-e2e.js.snap
Puts the `ignoreExportsUsedInFile` properties all on one line, to reduce snapshot size.
=> chore: align knip.jsonc lines to Prettier

src/steps/writing/writeStructure.test.ts, src/steps/writing/writeStructure.ts
Wraps the `chmod` with a `try`/`catch`. I figure if it fails then that's probably a sign the running OS doesn't have it and therefore doesn't need it.
=> fix: allow chmod to fail in setup

script/__snapshots__/migrate-test-e2e.js.snap, src/steps/writing/creation/writePackageJson.test.ts, src/steps/writing/creation/writePackageJson.ts
Sets `pnpm` to always reference the current latest `pnpm@8.14.0`. Removes the unnecessary diff in the migration test snapshot.
=> chore: unify pnpm @8.14.0

src/steps/initializeGitHubRepository/labels/outcomeLabels.ts
Changes the color for the `area:testing`  label to `#1177AA`
=> chore: change label color for area:testing

script/__snapshots__/migrate-test-e2e.js.snap, script/migrate-test-e2e.js, src/steps/updateLocalFiles.test.ts, src/steps/updateLocalFiles.ts
Gates those elements of `replacements` behind `options.mode` not being `"migrate"`. Which means the end-to-end migration snapshot for `.github/DEVELOPMENT.md` no longer shows removing `## Setup Scripts`! Yay!
=> fix: skip replacing existing tooling in --mode migrate

docs/FAQs.md
I was going to change my prettier settings from tabs to spaces until I discovered that GitHub has a setting that lets you change the tab size from the default of 8. If I'd had this set to 2 (my preference) before setting up my repo, I probably wouldn't have even noticed that I was using tabs!
=> docs: mention GitHub tab size setting

.github/workflows/test-create.yml, .github/workflows/test-initialize.yml, .github/workflows/test-migrate.yml, .github/workflows/test.yml, script/__snapshots__/migrate-test-e2e.js.snap
=> chore: don't upload code coverage as GHA artifacts

package.json, script/__snapshots__/migrate-test-e2e.js.snap, src/steps/writing/creation/writePackageJson.test.ts, src/steps/writing/creation/writePackageJson.ts
Directly replaces `prettier "**/*" --ignore-unknown` with `prettier .` per Prettier's blog post.
=> chore: use prettier .

script/__snapshots__/migrate-test-e2e.js.snap, script/migrate-test-e2e.js, src/steps/writing/creation/writePackageJson.ts
Changes `package.json` creation to preserve any existing `scripts`.
=> fix: preserve existing package.json scripts

.github/workflows/lint.yml, src/shared/createCleanupCommands.test.ts, src/shared/createCleanupCommands.ts, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
Uses the lovely, newly-discovered-by-me `--no-dts` option. Now the builds done before CI linting (when `options.bin` is enabled) and in the cleanup commands should be much faster.
=> perf: use --no-dts in cleanup and pre-lint builds

.eslintrc.cjs, src/steps/writing/creation/createESLintRC.test.ts, src/steps/writing/creation/createESLintRC.ts
Disables the `jsonc/comma-dangle` rule altogether so as to not conflict with Prettier. I suppose if any tool doesn't support trailing commas in a file, it'll report that directly. And most tools generally support jsonc anyway. 🤷
=> fix: disable jsonc/comma-dangle

src/create/createRerunSuggestion.test.ts, src/create/createRerunSuggestion.ts
Adds a `defaultValues` map and filters out key/value pairs matched in it.
=> fix: omit default --access value in rerun suggestions

src/create/createRerunSuggestion.test.ts, src/create/createRerunSuggestion.ts
Applies a couple of bits of good normalization to printed options:
* Removes the manual `--mode` so it doesn't get duplicated
* Sets the relevant `skip*` options to `undefined` if `options.offline` is enabled
Also adds some unit tests around partial options, as that was missing before.
=> fix: don't suggest --skip options in rerun if --offline

src/steps/initializeBranchProtectionSettings.test.ts, src/steps/initializeGitHubRepository/initializeBranchProtectionSettings.ts
This way, when creating/initializing/migrating a repository, branch protection settings won't be created for excluded options' CI flows.
=> fix: gate branch protection settings on options exclusions

.github/ISSUE_TEMPLATE/03-feature.yml, src/steps/writing/creation/dotGitHub/issueTemplate.ts
Updates the file and template for it.
=> fix: don't ask to restart IDE in feature template

.github/workflows/accessibility-alt-text-bot.yml, src/steps/writing/creation/dotGitHub/createWorkflowFile.ts, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
See linked issue. I set this up in my repo in https://github.com/danvk/gravlax/pull/58 following https://github.com/typescript-eslint/typescript-eslint/pull/8212. We can wait for a few renovate bot updates on my repo to confirm that this has the desired effect.
I added support for top-level `if` statements on jobs. It's possible to skip an individual step (which is already supported) but skipping the entire job seems more correct: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
=> ci: do not run accessibility checks for bots

.eslintrc.cjs, package.json, pnpm-lock.yaml, script/__snapshots__/migrate-test-e2e.js.snap, src/steps/writing/creation/createESLintRC.test.ts, src/steps/writing/creation/createESLintRC.ts
Switches to the `recommended-legacy` plugin and bumps `eslint-plugin-markdown` to the latest version, 4.x.
=> fix: use plugin:markdown/recommended-legacy

.github/renovate.json, src/steps/writing/creation/dotGitHub/createDotGitHubFiles.ts
Altogether stops repositories from being upgraded to `codecov/codev-action@v4`. 
This can always be revisited if & when Codecov provides more details on tokenless uploads (https://github.com/codecov/codecov-action/issues/1293).
=> fix: ignore codecov-action in renovate.json

package.json, pnpm-lock.yaml, src/steps/uninstallPackages.ts
Removes the devDependency and its uninstallation.
=> chore: remove @types/prettier

.eslintrc.cjs, src/steps/writing/creation/createESLintRC.test.ts, src/steps/writing/creation/createESLintRC.ts
=> feat: remove no-padding-line-between-statements

.eslintrc.cjs, src/shared/options/augmentOptionsWithExcludes.ts, src/shared/options/ensureRepositoryExists.ts, src/steps/writing/creation/createESLintRC.test.ts, src/steps/writing/creation/createESLintRC.ts
Removes the disable of the rule, and adds `{}` blocks around the two violations in the code base.
=> feat: remove disable of no-case-declarations

.github/actions/prepare/action.yml, package.json, src/steps/writing/creation/dotGitHub/actions.test.ts, src/steps/writing/creation/dotGitHub/actions.ts, src/steps/writing/creation/writePackageJson.test.ts, src/steps/writing/creation/writePackageJson.ts
Right now, trying to use `create-typescript-app` with anything but the _exact correct pnpm major.minor.patch version_ installed produces an error. That's very annoying.
Pending https://github.com/nodejs/corepack/issues/95, removes usage of the [experimental `package.json` `packageManager` field](https://nodejs.org/api/packages.html#packagemanager).
=> fix: remove package.json packageManager field

package.json, pnpm-lock.yaml, src/shared/options/getGitHub.test.ts, src/shared/options/getGitHub.ts, src/steps/uninstallPackages.ts
Swaps out `gh auth token` with `await getGitHubAuthToken()`. Doesn't fully remove the dependency on `gh`.
💖
=> feat: use get-github-auth-token instead of gh auth token

eslint.config.js, package.json, pnpm-lock.yaml, script/__snapshots__/migrate-test-e2e.ts.snap, script/migrate-test-e2e.ts, src/shared/options/createOptionDefaults/readDefaultsFromDevelopment.ts, src/shared/options/createOptionDefaults/readDefaultsFromReadme.ts, src/steps/writing/creation/createESLintConfig.test.ts, src/steps/writing/creation/createESLintConfig.ts, src/steps/writing/creation/rootFiles.ts, tsconfig.json
Also removes an unnecessary `"outDir": "lib"` from the `tsconfig.json`. It's a holdover from when `tsc` was used to compile to the `lib/` directory.
💖
=> feat: typescript-eslint@8

eslint.config.js, package.json, pnpm-lock.yaml, src/bin/help.test.ts, src/shared/cli/outro.test.ts, src/shared/doesRepositoryExist.test.ts, src/shared/getGitHubUserAsAllContributor.test.ts, src/shared/options/augmentOptionsWithExcludes.ts, src/shared/options/readOptions.ts, src/shared/prompts.ts, src/shared/readFileSafe.ts, src/shared/readFileSafeAsJson.ts, src/steps/initializeBranchProtectionSettings.test.ts, src/steps/initializeGitHubRepository/labels/initializeRepositoryLabels.ts, src/steps/writing/creation/createESLintConfig.test.ts, src/steps/writing/creation/createESLintConfig.ts, src/steps/writing/creation/dotGitHub/createWorkflowFile.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts, src/steps/writing/creation/dotGitHub/index.ts, src/steps/writing/creation/writePackageJson.ts, src/steps/writing/types.ts
Bumps to `eslint-plugin-perfection@3` and runs `pnpm lint --fix` for all its behavior differences.
💖
=> fix: support eslint-plugin-perfectionist@3

.github/renovate.json, cspell.json, src/steps/writing/creation/dotGitHub/createDotGitHubFiles.test.ts, src/steps/writing/creation/dotGitHub/createDotGitHubFiles.ts
Removes `"internalChecksFilter": "strict"` because that's the default value.
Adds some unit tests because `createDotGitHubFiles` wasn't unit tested before, too.
💖
=> feat: configure Renovate to skip patch updates

script/__snapshots__/migrate-test-e2e.ts.snap, src/steps/writeReadme/findIntroSectionClose.test.ts, src/steps/writeReadme/findIntroSectionClose.ts
Adds a special case for a README.md already having a CTA-style project logo image.
💖
=> fix: preserve post-badge paragraph in README.md migration

src/shared/createCleanupCommands.test.ts, src/shared/createCleanupCommands.ts, src/steps/finalizeDependencies.test.ts, src/steps/finalizeDependencies.ts
Doesn't impact `pnpm lint:packages`, just the migration/setup scripts.
💖
=> fix: run pnpm dedupe --offline in cleanups

.github/actions/prepare/action.yml, src/steps/writing/creation/dotGitHub/actions.test.ts, src/steps/writing/creation/dotGitHub/actions.ts
This PR upgrades the `pnpm/action-setup@v2` to `pnpm/action-setup@v4` which should resolve the warning.
From the looks of the releases page, 3 would work as well: https://github.com/pnpm/action-setup/releases
=> fix: upgrade pnpm/action-setup to v4

src/steps/writing/creation/dotVSCode.test.ts, src/steps/writing/creation/dotVSCode.ts
This PR excludes the extension for linting Markdown if the option specifies excluding that.
=> fix: should not include extensions for markdown when excluded

eslint.config.js, package.json, pnpm-lock.yaml, src/steps/writing/creation/createESLintConfig.test.ts, src/steps/writing/creation/createESLintConfig.ts
Uses the configs instead of previous manual rule configurations.
💖
=> feat: adopt granular eslint-plugin-jsdoc configs

.vscode/extensions.json, src/steps/writing/creation/dotVSCode.test.ts, src/steps/writing/creation/dotVSCode.ts
This PR adds the Vitest Explorer extension
=> feat: include vitest.explorer VS Code extension

src/initialize/index.test.ts, src/initialize/initializeWithOptions.test.ts, src/shared/runOrRestore.ts
As the issue suggested, this was a fair bit of setup. But I feel better now.
Also swaps out a `0` that was just coincidentally the same as the proper `StatusCodes.Success`.
💖
=> test: finish unit testing initialize and initializeWithOptions

src/steps/finalizeDependencies.test.ts, src/steps/finalizeDependencies.ts
Adds `options.*` checking in `finalizeDependencies`, to better restrict what gets installed.
💖
=> fix: remove unnecessary devDependencies for --base common

.github/workflows/post-release.yml, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
Uses the same `{release_tag}` as the _GitHub releases_ link.
💖
=> fix: simplify post-release.yml with release_tag instead of npm pkg get

.github/workflows/post-release.yml, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
Uses `${{ payload.release.tag_name }}` this time, as suggested.
💖
=> fix: use payload.release.tag_name for npm package release

docs/FAQs.md, docs/Options.md
Clarify what `bin` does and does not do.
=> docs: clarify the purpose of --bin

.vscode/settings.json, src/steps/writing/creation/dotVSCode.test.ts, src/steps/writing/creation/dotVSCode.ts
=> fix: remove outdated vscode-eslint eslint.useFlatConfig setting

eslint.config.js, package.json, pnpm-lock.yaml, script/__snapshots__/migrate-test-e2e.ts.snap, src/steps/writing/creation/createESLintConfig.test.ts, src/steps/writing/creation/createESLintConfig.ts, src/steps/writing/creation/dotVSCode.test.ts
Applies the changes in the issue. This brings the file line count -including comments- from 166 to 140.
Removes the `files: ["**/*.md/*.ts"],` from this repo's `eslint.config.js` because there's no `ts` codeblock in the README.md.
Updates the `typescript-eslint` package by necessity for the `defaultProject` default.
💖
=> feat: streamlined eslint.config.js with better tseslint.config usage

.gitignore, .prettierignore, script/__snapshots__/migrate-test-e2e.ts.snap, src/steps/writing/creation/createDotGitignore.test.ts, src/steps/writing/creation/createDotGitignore.ts, src/steps/writing/creation/rootFiles.ts
Per https://git-scm.com/docs/gitignore#_pattern_format, uses preceding `/` slashes to indicate directories and files that should only be matched at the root. Which is all of them.
The Git docs also noted that a trailing `/` makes the pattern only match directories. Since these are known directory names that won't be swapped with files accidentally, I took out any trailing `/`s to keep the files as small as possible.
Aside: Per https://lore.kernel.org/git/pull.1720.git.git.1715705582609.gitgitgadget@gmail.com, I'm pretty sure the Git docs have a small typo. But per https://lore.kernel.org/git/xmqqseyk2hce.fsf@gitster.g I don't know that it'll get resolved soon.
💖
=> fix: use root-level slashes in .gitignore and .prettierignore

cspell.json, docs/FAQs.md, script/__snapshots__/migrate-test-e2e.ts.snap
Removes `precommit` from `cspell.json`, hooray.
💖
=> docs: correct pre(-)commit typo

.github/DEVELOPMENT.md, .github/workflows/ci.yml, script/__snapshots__/migrate-test-e2e.ts.snap, src/steps/writing/creation/dotGitHub/createMultiWorkflowFile.ts, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
=> chore: move e2e migration scripts into ci.yml

.github/DEVELOPMENT.md, script/__snapshots__/migrate-test-e2e.ts.snap, src/steps/writing/creation/dotGitHub/createDevelopment/index.test.ts, src/steps/writing/creation/dotGitHub/createDevelopment/index.ts
Mostly re-applies changes from #1670.
💖
=> docs: streamlined and organized DEVELOPMENT.md

eslint.config.js, script/__snapshots__/migrate-test-e2e.ts.snap, script/migrate-test-e2e.ts, tsconfig.json
=> chore: move script/ inclusion to TSConfig

.github/workflows/post-release.yml, src/next/blocks/blockReleaseIt.ts, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts
This PR applies the change suggested by @apexskier here to attempt to fix post-release permissions:
https://github.com/apexskier/github-release-commenter/issues/545#issuecomment-2513388057
=> fix: post release permissions error

.github/workflows/ci.yml, script/__snapshots__/migrate-test-e2e.ts.snap
Adds the `env:` addition internally.
Doesn't add it to created repos, because I think most consumers aren't going to be hitting the Codecov 429 rate limits very often. I don't want them to have to add a _third_ new token to their repos.
💖
=> chore: use codecov token for CI test runs internally

src/next/blocks/blockReleaseIt.ts
Marking as a `chore:` because this only impacts when opting into the new `create` engine with the undocumented `CTA_CREATE_ENGINE` flag.
💖
=> chore: correct missing release-it dependencies for blockReleaseIt

src/next/blocks/blockRepositoryBranchRuleset.ts, src/steps/initializeBranchProtectionSettings.test.ts, src/steps/initializeGitHubRepository/initializeBranchProtectionSettings.ts
Pending being told contrary information, hardcodes `actor_id: 5` for the repository role to always be allowed to bypass branch protection ruleset. 
💖
=> fix: bypass repository admin (id 5) in branch ruleset

knip.json, script/__snapshots__/migrate-test-e2e.ts.snap, src/next/blocks/blockKnip.ts, src/next/blocks/packageData.ts, src/steps/writing/creation/createKnipConfig.test.ts, src/steps/writing/creation/createKnipConfig.ts, src/steps/writing/creation/rootFiles.ts
Uses the same `readFileSafeAsJson` strategy as `writePackageJson`.
💖
=> fix: use Knip version from installed dependency

src/shared/options/readOptions.test.ts, src/shared/options/readOptions.ts, src/shared/packages.ts
When `mode` is `"create"`, `options.skipRestore` now has an additional `??` to set it to `true`.
Most of the time spent here is adjusting mocks, since `readOptions` previously always ran in that mode. Looking forward to the new `create` engine to make this much more automatic and inferred. 😎 
💖
=> fix: default skipRestore to true when mode is create

src/next/blocks/blockAllContributors.test.ts, src/next/blocks/blockAllContributors.ts, src/shared/getGitHubUserAsAllContributor.test.ts, src/shared/getGitHubUserAsAllContributor.ts, src/steps/addToolAllContributors.test.ts, src/steps/addToolAllContributors.ts, src/steps/updateAllContributorsTable.ts
=> fix: use pnpx, not npx

script/__snapshots__/migrate-test-e2e.ts.snap, src/next/base.ts, src/next/blocks/packageData.ts, src/next/blocks/sourcePackageJson.ts, src/next/readDescription.test.ts, src/next/readDescription.ts, src/shared/options/createOptionDefaults/index.ts
Applies both in the legacy mode and new create mode.
💖
=> fix: don't infer --description if it's the source default

src/create/createRerunDirectorySuggestion.test.ts, src/create/createRerunDirectorySuggestion.ts, src/create/createRerunSuggestion.test.ts, src/create/createRerunSuggestion.ts
=> fix: don't suggest redundant --directory

README.md, docs/Options.md, package.json, pnpm-lock.yaml, src/bin/help.test.ts, src/next/base.ts, src/next/blocks/blockREADME.test.ts, src/next/blocks/blockREADME.ts, src/shared/options/args.ts, src/shared/options/createOptionDefaults/readDefaultsFromReadme.test.ts, src/shared/options/createOptionDefaults/readDefaultsFromReadme.ts, src/shared/options/logInferredOptions.ts, src/shared/options/readLogoSizing.test.ts, src/shared/options/readLogoSizing.ts, src/shared/options/readOptions.ts, src/shared/types.ts, src/steps/uninstallPackages.ts, src/steps/writing/creation/index.test.ts
Uses [`image-size`](https://github.com/image-size/image-size) to read from disk, if possible.
Caps sizes to 128px. Doesn't bother adding a warning logo - I don't feel strongly about it, and have yet to have come across a situation where I would have been helped by that.
💖
=> feat: add logo.height and logo.width

package.json, src/steps/writing/creation/index.test.ts
The fact that this wasn't reported by anybody else or fixed yet is an amusing indicator of how rarely _Use this template_ button is used.
💖
=> fix: build in initialize script

.all-contributorsrc, .prettierignore, script/__snapshots__/migrate-test-e2e.ts.snap, src/next/blocks/blockAllContributors.test.ts, src/next/blocks/blockAllContributors.ts, src/next/blocks/blockTypeScript.test.ts, src/next/blocks/blockTypeScript.ts, src/next/blocks/blockVitest.test.ts, src/next/blocks/blockVitest.ts, src/steps/writing/creation/rootFiles.ts, vitest.config.ts
Also fixes #1817 while I'm in the area.
💖
=> fix: remove redundant coverage.exclude: lib from vitest.config.ts

src/next/base.ts, src/shared/options/createOptionDefaults/index.test.ts, src/shared/options/createOptionDefaults/index.ts, src/shared/options/createOptionDefaults/readDefaultsFromReadme.test.ts, src/shared/options/createOptionDefaults/readDefaultsFromReadme.ts
Moves `repository` into its own separate `lazyValue` that's then used for `usage`.
Also allows `repository` to default to `options.directory`.
💖
=> fix: lazily evaluate options.repository for options.usage

src/shared/options/readLogoSizing.test.ts, src/shared/options/readLogoSizing.ts
Adds the extra `type: "ping"` to tests to be sure.
💖
=> fix: don't include non-size properties in logo option

src/next/blocks/blockMarkdownlint.test.ts, src/next/blocks/blockMarkdownlint.ts, src/next/blocks/blockPrettier.test.ts, src/next/blocks/blockPrettier.ts
Resists the urge to move the common `.sort()` inside the function, since not every consumer does that.
💖
=> chore: use formatIgnoreFile in remaining blocks

src/next/blocks/blockESLint.test.ts, src/next/blocks/blockESLint.ts, src/steps/writing/creation/createESLintConfig.ts, src/steps/writing/creation/index.test.ts
=> fix: include options.bin in ESLint allowDefaultProject

.github/DEVELOPMENT.md, src/next/blocks/blockDevelopmentDocs.test.ts, src/next/blocks/blockDevelopmentDocs.ts, src/steps/writing/creation/dotGitHub/createDevelopment/index.test.ts, src/steps/writing/creation/dotGitHub/createDevelopment/index.ts
=> fix: use parenthesis for development your-name-here script

.github/DEVELOPMENT.md, .github/workflows/ci.yml, .vscode/launch.json, docs/FAQs.md, package.json, script/__snapshots__/migrate-test-e2e.ts.snap, script/create-test-e2e.ts, script/initialize-test-e2e.ts, script/migrate-test-e2e.ts, src/next/blocks/blockPackageJson.test.ts, src/next/blocks/blockPackageJson.ts, src/next/blocks/blockTSup.test.ts, src/next/blocks/blockTSup.ts, src/next/blocks/blockTypeScript.test.ts, src/next/blocks/blockTypeScript.ts, src/shared/options/createOptionDefaults/index.test.ts, src/steps/writing/creation/dotGitHub/createDotGitHubFiles.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.test.ts, src/steps/writing/creation/dotGitHub/createWorkflows.ts, src/steps/writing/creation/index.test.ts, src/steps/writing/creation/writePackageJson.test.ts, src/steps/writing/creation/writePackageJson.ts
There are now no `./` instances in the `package.json` file. Nice.
💖
=> fix: remove ./ prefixes in package.json bin and main

src/next/blocks/blockPackageJson.test.ts, src/next/blocks/blockPackageJson.ts
2af82047f897b861a827e1bac4ea8ccf11fa800d shows the `\n` in the test.
💖
=> fix: don't wrap words in blockPackageJson description

src/next/base.ts, src/next/blocks/blockREADME.test.ts, src/next/blocks/blockREADME.ts, src/shared/options/createOptionDefaults/readDefaultsFromReadme.test.ts, src/shared/options/createOptionDefaults/readDefaultsFromReadme.ts
Also touches up some spacing and tests in `readDefaultsFromReadme`, while I'm in the area.
💖
=> feat: add options.explainer for blockREADME

src/next/blocks/blockCodecov.test.ts, src/next/blocks/blockCodecov.ts, src/next/blocks/blockContributingDocs.test.ts, src/next/blocks/blockContributingDocs.ts, src/next/blocks/blockContributorCovenant.test.ts, src/next/blocks/blockContributorCovenant.ts, src/next/blocks/blockDevelopmentDocs.test.ts, src/next/blocks/blockDevelopmentDocs.ts, src/next/blocks/blockESLint.ts, src/next/blocks/blockGitHubActionsCI.test.ts, src/next/blocks/blockGitHubActionsCI.ts, src/next/blocks/blockKnip.ts, src/next/blocks/blockPackageJson.ts, src/next/blocks/blockPrettier.ts, src/next/blocks/blockTSup.test.ts, src/next/blocks/blockTSup.ts, src/next/blocks/blockVitest.test.ts, src/next/blocks/blockVitest.ts
Corresponding to https://github.com/JoshuaKGoldberg/create/pull/137.
💖
=> fix: run migration rm scripts with silent: true

src/next/blocks/blockGitHubActionsCI.test.ts, src/next/blocks/blockGitHubActionsCI.ts
=> fix: pass job names from blockGitHubActionCI to blockRepositoryBranchRuleset

knip.json, package.json, pnpm-lock.yaml
Saw that `remove-dependencies` caused the knip lint task to fail in this repo, which made me see and fix the issue with `"all-contributors-cli"` and wrap things up here :)
=> chore: upgrade knip & config

README.md, docs/Creation.md, docs/Initialization.md, docs/Migration.md, docs/Options.md
=> docs: mention being in @beta

.release-it.json, src/blocks/blockReleaseIt.ts
This change adjusts the release-it config for both this repo, as well as what the create script generates, so that the previous changes to enhance the changelog generation flows through to the github release page too.
I discussed this here release-it/release-it#1025 (comment), and @webpro theorized it was the autoGenerate that overrode the changelog output from being applied to the GH release too.
I created a test repo to verify and confirmed that removing `autoGenerate`, indeed, fixed the issue: https://github.com/michaelfaith/mf-cta-testing/releases 2.0.2 is after this change, which included both a chore change and fix change, but changelog and GH release page only show the bug fix (notice also the group heading, which isn't in the previous releases). 2.0.1 is before the change, with …
=> fix: don't include chore PRs in GH release page

src/base.ts, src/blocks/blockAllContributors.ts, src/data/contributions.ts, src/inputs/inputFromOctokit.ts, src/options/readAllContributors.test.ts, src/options/readAllContributors.ts
The previous `pnpx all-contributors-cli` command was only enough for transition mode to pick up on existing contributors and create a README.md section. For setup mode, there needed to be a default in options if `.all-contributorsrc` doesn't yet exist. That's now pulled from the GitHub API.
🎁
=> fix: add README.md contributors section in setup

.github/actions/prepare/action.yml, package.json, src/base.test.ts, src/base.ts, src/blocks/blockGitHubActionsCI.test.ts, src/blocks/blockGitHubActionsCI.ts, src/blocks/blockPackageJson.test.ts, src/blocks/blockPackageJson.ts, src/options/readPnpm.test.ts, src/options/readPnpm.ts, src/types.ts
Adds a `pnpm` option to the Base, which defaults to the existing `packageManager`'s pnpm version if it exists.
🎁
=> feat: add packageManager back to package.json, and set to pnpm 10.4.0 in CI

docs/Blocks.md, src/blocks/blockTSup.test.ts, src/blocks/blockTSup.ts, src/blocks/blockTypeScript.test.ts, src/blocks/blockTypeScript.ts, tsconfig.json, tsup.config.ts
Per discussions linked in the issue, removes sourcemaps to significantly reduce the size of output files.
| Target              | Package Size | Unpacked Size | Total Files |
| ------------------- | ------------ | ------------- | ----------- |
| `main`              | 106.7 kB     | 609.9 kB      | 277         |
| `remove-sourcemaps` | 54.1 kB      | 369.9 kB      | 186         |
| Comparison          | 49% smaller  | 39% smaller   | 32% smaller |
Raw `npm pack` output on `main`:
```plaintext
npm notice Tarball Details
npm notice name: create-typescript-app
npm notice version: 2.2.0
npm notice filename: create-typescript-app-2.2.0.tgz
npm notice package size: 106.7 kB
npm notice unpacked size: 609.9 kB
npm notice shasum: dd0439e3a977c55bbfaa8449f73799314b925368
npm notice integrity: …
```
=> feat: remove sourcemaps

src/blocks/blockRepositoryBranchRuleset.test.ts, src/blocks/blockRepositoryBranchRuleset.ts
If `options.rulesetId` doesn't exist, then transition mode should still `POST` a new ruleset, not `PUT` to update an existing one.
🎁
=> fix: only PUT a ruleset when an ID already exists

src/options/readAllContributors.test.ts, src/options/readAllContributors.ts
The `GET /user` result can be `undefined` if the user isn't logged in.
🎁
=> fix: don't crash reading contributors when not logged into GitHub

docs/CLI.md, package.json, pnpm-lock.yaml, src/base.ts, src/blocks/blockESLint.ts, src/blocks/blockExampleFiles.ts, src/blocks/blockPackageJson.ts, src/blocks/blockRepositoryBranchRuleset.ts, src/blocks/blockVSCode.ts, src/blocks/blockVitest.test.ts, src/docsBlocks.test.ts, src/inputs/inputFromOctokit.ts, src/options/readGitDefaults.test.ts, src/options/readGitDefaults.ts, src/options/readLogoSizing.ts, src/options/readNpmDefaults.ts, src/utils/resolveBin.ts, src/utils/sortObject.ts
Cleans up some pending code TODOs:
* Bumping `@vitest/eslint-plugin` to include https://github.com/vitest-dev/eslint-plugin-vitest/pull/682
* Refactors `retGitDefaults` to execute a straightforward `git remote get-url origin` instead of the full `git-remote-origin-url`
* Uses [`sort-keys`](http://npmjs.com/package/sort-keys) instead of the ad-hoc internal `sortKeys`
* Uses [`zod-package-json`](http://npmjs.com/package/zod-package-json) instead of a manually written schema
Otherwise doesn't change behavior, instead adding links to:
* #1990
* #1991
* #1992
* #1993
🎁
=> fix: use standard packages or link to issues for remaining code TODOs

docs/Configuration Files.md, package.json, pnpm-lock.yaml, src/base.test.ts, src/base.ts, src/blocks/actions/printUses.ts, src/blocks/actions/resolveUses.test.ts, src/blocks/actions/resolveUses.ts, src/blocks/blockAllContributors.ts, src/blocks/blockCTATransitions.ts, src/blocks/blockCodecov.ts, src/blocks/blockGitHubActionsCI.ts, src/blocks/blockPRCompliance.ts, src/blocks/blockReleaseIt.ts, src/blocks/files/createMultiWorkflowFile.ts, src/blocks/files/formatYaml.ts, src/blocks/files/removeUsesQuotes.test.ts, src/blocks/files/removeUsesQuotes.ts, src/inputs/inputFromDirectory.ts, src/options/readWorkflowsVersions.ts, src/schemas.ts
Adds a new `workflowsVersions` option that reads in any existing pins and comment hashes.
Printing out comment hashes is actually tricky: they're not part of the AST, so I had to add a post-processing step after YAMl printing to turn any `uses:` string ending with a `#` comment back from `uses: '... # ...'` to `uses: ... # ...`.
Skips adding tests for `readWorkflowVersions` pending https://github.com/JoshuaKGoldberg/bingo/issues/308.
🎁
=> fix: preserve GitHub Actions hashes and versions

src/blocks/blockCTATransitions.test.ts, src/blocks/blockCTATransitions.ts, src/blocks/blockGitHubActionsCI.ts, src/blocks/files/createSoloWorkflowFile.ts, src/blocks/files/formatYamlAction.ts
Moves the transition mode logic into two files:
1. `.github/actions/transition/action.yml`: A dedicated composite action for running in transition mode and checking in & commenting any changes
2. `.github/workflows/cta.yml`: Checks if the action should be run, and runs it if so
This means the job won't be marked as _Skipped_ if the logic is skipped. It'll still be _Success_ and thus not block PRs.
🎁
=> feat: standalone CTA Transitions workflow

src/options/readLogo.test.ts, src/options/readLogo.ts
Ignores:
* Alt text of `All Contributors: \d+`
* Source images from `img.shields.io`
🎁
=> fix: ignore known badges when reading logo

package.json, pnpm-lock.yaml, src/base.ts, src/blocks/blockCSpell.test.ts, src/blocks/blockRepositoryBranchRuleset.test.ts, src/blocks/blockRepositoryBranchRuleset.ts, src/blocks/options.fakes.ts
Includes updates to the latest Bingo packages to bring in silent requests: https://github.com/JoshuaKGoldberg/bingo/pull/313
I would have liked to go with a rename or archive kind of API, even changing the protection to be on some branch like `main-prior-to-cta`. But such a GitHub API does not exist. 🤷 
🎁
=> feat: remove legacy main branch protections in ruleset transition mode

docs/Blocks.md, src/blocks/blockNcc.test.ts, src/blocks/blockNcc.ts, src/blocks/index.ts, src/template.ts
=> feat: add ncc builder block

src/base.ts, src/blocks/bin/getPrimaryBin.test.ts, src/blocks/bin/getPrimaryBin.ts, src/blocks/blockPackageJson.test.ts, src/blocks/blockPackageJson.ts, src/blocks/blockTypeScript.ts, src/blocks/blockVSCode.ts, src/types.ts
Updates the `PartialPackageData` type to note that `bin` could be a `Record<string, string>`, not just a `string`. `blockPackageJson` will collect its values if it is an object.
Also updates other references to `options.bin` to use a new `getPrimaryBin` function for determining what the main runner is. Per https://docs.npmjs.com/cli/v11/configuring-npm/package-json#bin using the same name as the repo is equivalent to using a string.
🎁
=> fix: support package.json bin objects

src/blocks/blockPackageJson.test.ts, src/blocks/blockPackageJson.ts
I couldn't figure out how to get the exact failure case from #2043, weirdly enough. But this PR's invalid semver handling happens to fix that failure in `debug-for-file` locally for me.
🎁
=> fix: coerce dependency versions in semver parsing

src/blocks/blockPackageJson.ts, src/blocks/blockRepositorySettings.test.ts, src/blocks/blockRepositorySettings.ts, src/blocks/html/htmlToTextSafe.ts
Reuses the existing `wordwrap: false` logic in a new shared `htmlToTextSafe` function. The fact that I didn't do this already is an indication of why it should be centralized.
🎁
=> fix: don't word-wrap long repo descriptions in API calls

docs/Blocks.md, src/blocks/blockMain.test.ts, src/blocks/blockMain.ts, src/blocks/blockPackageJson.test.ts, src/blocks/blockPackageJson.ts, src/blocks/blockTSup.test.ts, src/blocks/blockTSup.ts, src/blocks/blockTypeScript.test.ts, src/blocks/blockTypeScript.ts, src/blocks/index.ts, src/integration.test.ts, src/presets/minimal.ts
Separates out the concept of a "main" file to into its own `blockMain`. `blockTSup` now takes in `runInCI` as a general list of steps after `pnpm build`.
🎁
=> feat: separate out blockMain

package.json, pnpm-lock.yaml, src/blocks/blockTSup.test.ts, src/blocks/blockTSup.ts, src/blocks/blockTypeScript.test.ts, src/blocks/blockTypeScript.ts
=> feat: allow customizing tsc, tsup builds

src/base.ts, src/blocks/blockPackageJson.test.ts, src/blocks/blockPackageJson.ts
Expands the `options.packageData` schema to allow them. These are the first allowlisted `package.json` properties that aren't manually combined with addons, so they're generally spread in `blockPackageJson`.
🎁
=> fix: perserve peerDependencies, peerDependenciesMeta in transition mode

src/blocks/blockAllContributors.test.ts, src/blocks/blockAllContributors.ts, src/data/contributions.ts, src/options/readAllContributors.test.ts, src/options/readAllContributors.ts
To work around https://github.com/all-contributors/cli/issues/371, any existing owner contributions are merged with the default starters.
🎁
=> fix: preserve existing owner contributions during transition

cspell.json, src/blocks/blockESLint.test.ts, src/blocks/blockESLint.ts, src/blocks/blockRenovate.ts
These used to not be in cspell-dicts. They are now.
🎁
=> fix: remove automerge, tseslint from cspell.json

src/blocks/blockMarkdownlint.test.ts, src/blocks/blockMarkdownlint.ts, src/blocks/blockReleaseIt.test.ts, src/blocks/blockReleaseIt.ts, src/blocks/blockTemplatedWith.test.ts, src/blocks/blockTemplatedWith.ts
_Setup_ mode already populated words as of #1794. I confirmed in https://github.com/JoshuaKGoldberg/eslint-fix-utils/pull/79 that `pnpm lint:spelling` passes without these.
🎁
=> fix: remove remaining manual cspell word additions

src/utils/resolveBin.ts
On Windows, file paths typically begin with a drive letter (e.g., `C:`). However, to conform to the `file://` URI scheme in Node.js, they must be prefixed with a slash (e.g., `/C:`), resulting in a correct file URL like `file:///C:/GHub/file.js`.
Currently, the `resolveBin` function does not properly handle this conversion and mistakenly outputs an absolute path with a leading slash, such as `/C:/GHub/file.js`. This format is invalid on Windows, where the correct absolute path should be `C:/GHub/file.js`.
Mishandling paths that start with a leading slash on Windows can cause them to be interpreted as relative to the current drive, leading to incorrect resolutions. This can result in an erroneous path with duplicated drive letters (like `C:/C:/GHub/file.js`).
To resolve this issue, we …
=> fix: update `resolveBin` to use `fileURLToPath` for cross-platform compatibility

src/blocks/blockVitest.test.ts, src/blocks/blockVitest.ts
Also fixes a yet-to-be-hit-by-users bug where only having `"node_modules"` there results in `[, "node_modules"]`.
🎁
=> fix: deduplicate Vitest excludes entries

src/base.ts, src/options/readBin.test.ts, src/options/readBin.ts, src/utils/trimPrecedingSlash.test.ts, src/utils/trimPrecedingSlash.ts
=> fix: trim preceding ./ from package.json bin

src/blocks/blockKnip.test.ts, src/blocks/blockKnip.ts, src/blocks/intake/intakeFileAsJson.test.ts, src/blocks/intake/intakeFileAsJson.ts
=> feat: infer Knip Addons from disk

.github/ISSUE_TEMPLATE/01-bug.yml, .github/ISSUE_TEMPLATE/02-documentation.yml, .github/ISSUE_TEMPLATE/03-feature.yml, .github/ISSUE_TEMPLATE/04-tooling.yml, src/blocks/blockAllContributors.test.ts, src/blocks/blockCTATransitions.test.ts, src/blocks/blockCTATransitions.ts, src/blocks/blockGitHubActionsCI.test.ts, src/blocks/blockGitHubActionsCI.ts, src/blocks/blockReleaseIt.test.ts, src/blocks/files/formatYaml.ts, src/blocks/files/formatYamlAction.ts
Whatever reason I had for having two different calls to `jsYaml.dump` is, I think, no longer there. This normalizes all YAML printing to go through the standard `formatYaml`. YAML files now always have a blank line between root-level properties.
🎁
=> fix: normalize yaml outputs to always use -1 lineWidth

.github/actions/prepare/action.yml, src/base.ts, src/blocks/blockCSpell.test.ts, src/blocks/blockGitHubActionsCI.test.ts, src/blocks/blockGitHubActionsCI.ts, src/blocks/blockNvmrc.test.ts, src/blocks/blockNvmrc.ts, src/blocks/blockPackageJson.test.ts, src/blocks/blockPackageJson.ts, src/blocks/options.fakes.ts
Switches `.github/actions/prepare/action.yml` to use the Node version requested by options, not a hardcoded `"20"`.
Also fixes the `node` option schema to no longer be marked `.optional()`. It was always inferred, so this was inaccurate.
🎁
=> fix: use options.node in CI prepare action

docs/CLI.md, src/base.ts, src/blocks/blockPackageJson.test.ts, src/blocks/blockPackageJson.ts, src/options/readKeywords.test.ts, src/options/readKeywords.ts, src/types.ts
Removes the removal & flat-mapping from spaces because keywords actually can have spaces in them. CLI folks will have to specify them individually.
🎁
=> fix: read keywords from package.json during transition

src/blocks/blockPackageJson.test.ts, src/blocks/blockPackageJson.ts
=> fix: allow overriding package.json type

docs/CLI.md, eslint.config.js, src/base.test.ts, src/base.ts, src/blocks/blockESLint.test.ts, src/blocks/blockESLint.ts, src/blocks/blockPackageJson.test.ts, src/blocks/blockPackageJson.ts, src/types.ts
Goes a different, more comprehensive direction than #2110. Instead of encouraging a `blockPackageJson` it promotes `type` to a top-level option. `--type commonjs` will now work if a user really wants.
`blockESLint` will now print its config as `eslint.config.mjs` if `options.type` is `"commonjs"`. It's still `eslint.config.js` otherwise.
🎁
=> feat: add options.type

src/options/readReadmeAdditional.test.ts, src/options/readReadmeAdditional.ts
=> fix: detect legacy 'based on' notices in README.md

package.json, pnpm-lock.yaml, src/base.ts, src/blocks/blockPackageJson.ts, src/blocks/blockRepositorySettings.test.ts, src/blocks/blockRepositorySettings.ts, src/blocks/html/htmlToTextSafe.ts, src/options/readDescription.test.ts, src/options/readDescription.ts, src/utils/htmlToTextSafe.ts
Makes parsing around HTML (`README.md`) vs. markdown (`package.json`) descriptions smarter. [`marked`](https://marked.js.org) in inline mode is used to parse existing `package.json` descriptions, before they're checked against the README.md one.
Also normalizes the output `package.json`'s `description` to be plain text, since neither GitHub nor npm support rich text (https://github.com/JoshuaKGoldberg/create-typescript-app/issues/1934#issuecomment-2776616064). Example improvement: https://github.com/JoshuaKGoldberg/eslint-plugin-erasable-syntax-only/pull/51/commits/c43f07b11c8bc42036c626900dc88743cdfbcb4c
🎁
=> feat: support parsing existing package.json descriptions as markdown

cspell.json, src/blocks/blockESLintPlugin.test.ts, src/blocks/blockESLintPlugin.ts
=> fix: correct blockESLintPlugin peerDependencies and config file name

src/blocks/blockESLint.test.ts, src/blocks/blockESLint.ts
=> fix: deduplicate blockESLint rule groups by comment

src/options/readReadmeAdditional.test.ts, src/options/readReadmeAdditional.ts, src/options/readReadmeFootnotes.test.ts, src/options/readReadmeFootnotes.ts
The two parts of README.md parsing for documentation that care about these notices are:
* `additional`: which cares about the _first_ notice
* `footnotes`: which cares about the _last_ notice
I considered merging the two `read*` functions into a single one, but figured I could save that refactor for if this gets even more complicated / intertwined.
🎁
=> fix: correct readme templated-by parsing for multiple indicators

src/options/readReadmeExplainer.test.ts, src/options/readReadmeExplainer.ts
https://github.com/JoshuaKGoldberg/prune-github-notifications didn't have a `## Usage` in its README.md, and instead of allowing all content until the next relevant h2 or end-of-file, the option was defaulting to `undefined`.
This reminds me that `blockREADME` hardcodes a `## Usage` in there - that's not an assumption I want to keep. But removing that assumption can be a followup.
🎁
=> fix: correct README.md parsing without an existing Usage h2

docs/Blocks.md, src/blocks/blockWebExt.test.ts, src/blocks/blockWebExt.ts, src/blocks/index.ts, src/template.ts
Adds an opt-in Block akin to `blockNcc`. It's based on the existing dev structure in https://github.com/JoshuaKGoldberg/refined-saved-replies.
🎁
=> feat: add blockWebExt for Web-ext builds

knip.json, src/blocks/blockKnip.test.ts, src/blocks/blockKnip.ts, src/blocks/blockTypeScript.test.ts, src/blocks/blockTypeScript.ts, src/blocks/blockVitest.test.ts, src/blocks/blockVitest.ts
Goes a bit beyond #2147's original intended scope of `entry` by also making `project` an Addon. This way, `blockTypeScript` and `blockVitest` fully communicate all file globs to `blockKnip`.
Also expands `blockKnip`'s `intake` to read both of those new Addon properties. This will allow customizations such as https://github.com/JoshuaKGoldberg/refined-saved-replies's `entry: ["src/content-script.ts"]` to be inferred.
🎁
=> feat: switch Knip entry and project to Addons

package.json, pnpm-lock.yaml, src/blocks/blockNcc.test.ts, src/blocks/blockNcc.ts
Includes bumps of `bingo-stratum` and `bingo-stratum-testers` so its `intake` can include `options` per https://github.com/JoshuaKGoldberg/bingo/issues/345.
🎁
=> feat: add entry addon for blockNcc

cspell.json, package.json, pnpm-lock.yaml, src/blocks/blockESLint.test.ts, src/blocks/blockESLint.ts, src/blocks/blockESLintIntake.test.ts, src/blocks/blockESLintMoreStyling.ts, src/blocks/eslint/blockESLintIntake.ts, src/blocks/eslint/schemas.ts, src/blocks/intake/intakeFile.ts, src/integration.test.ts, src/utils/tryCatch.ts
This is one of the more ridiculous things I've written recently. It:
1. Attempts to parse existing `eslint.config.{js,mjs}` content as a [`@typescript-eslint/typescript-estree`](https://typescript-eslint.io/packages/typescript-estree) tree
2. Find the `{ ignores: [...] }` from its first argument
3. Find the next `{ rules: ... }` from its remaining arguments
4. Parse rules groups using [JSON5.parse](https://www.npmjs.com/package/json5)
...and only if all steps return something looking like what we expect do we give back some data.
This is really beyond what I'd want folks to have to write in `intake`. I really wish for this all to be done automatically and reliably: https://github.com/JoshuaKGoldberg/bingo/issues/128. But that's going to be a lot more work I don't have time for soon.
🎁
=> feat: add intake method to blockESLint

src/blocks/blockTSup.test.ts, src/blocks/blockTSup.ts, src/blocks/blockVitest.test.ts, src/blocks/blockVitest.ts, src/blocks/intake/intakeFile.test.ts, src/blocks/intake/intakeFileDefineConfig.test.ts, src/blocks/intake/intakeFileDefineConfig.ts
Extracts `defineConfig` parsing into a shared `intakeFileDefineConfig`. Also fills in remaining tests for `intakeFile` while I'm here.
🎁
=> feat: add intake to blockTSup

src/blocks/blockESLintIntake.test.ts, src/blocks/eslint/blockESLintIntake.ts
=> fix: correct blockESLint intake multi-line comment parsing

package.json, pnpm-lock.yaml, src/blocks/blockAllContributors.test.ts, src/blocks/blockAllContributors.ts
Uses `null, 2` as JSON.stringify settings - which matches https://github.com/all-contributors/cli/blob/74bc388bd6f0ae2658e6495e9d3781d737438a97/src/util/formatting.js#L2.
🎁
=> fix: print .all-contributorsrc with two spaces

src/blocks/blockAllContributors.test.ts, src/blocks/blockAllContributors.ts, src/blocks/blockRenovate.test.ts, src/blocks/blockRenovate.ts, src/blocks/blockTypeScript.test.ts, src/blocks/blockTypeScript.ts
Also standardizes `blockTypeScript` to use the newer `intakeFileAsJson`, while I'm in the area.
🎁
=> feat: add ignoreDeps Addon to blockRenovate

.github/renovate.json, src/integration.test.ts
Along with #2180, this will keep `all-contributors-cli` on the version that ignores Prettier. Because the app does too.
🎁
=> fix: stop all-contributors-cli from being updated beyond 6.26.1

src/blocks/blockCSpell.test.ts, src/blocks/blockContributorCovenant.test.ts, src/blocks/blockContributorCovenant.ts, src/blocks/blockMarkdownlint.test.ts, src/blocks/blockMarkdownlint.ts, src/blocks/blockReleaseIt.test.ts, src/blocks/blockReleaseIt.ts
=> feat: add ignores Addon for blockMarkdownlint

src/blocks/blockESLintPlugin.test.ts, src/blocks/blockESLintPlugin.ts, src/blocks/eslint/blockESLintPluginIntake.ts, src/blocks/eslint/schemas.ts
Uses a similar AST parsing strategy as `blockESLintIntake` to find a `const config = `.
🎁
=> feat: added configEmoji Addon to blockESLintPlugin

src/blocks/blockCTATransitions.test.ts, src/blocks/blockCTATransitions.ts
Upstreaming of https://github.com/JoshuaKGoldberg/formatly/pull/122. Previously, the action would only check on step 2 of 3 `if` it should skip. But step 1 -checkout- requires a token that doesn't exist on fork.
Now, step 1 does the `if`. No more checking out the repo unnecessarily.
🎁
=> fix: skip checkout in CTA action before transition step

package.json, pnpm-lock.yaml, src/blocks/blockVitest.test.ts
Bumps:
```plaintext
@vitest/coverage-v8  3.0.9  →  3.2.4
vitest               3.0.9  →  3.2.4
```
🎁
=> fix: bump vitest to 3.2.4

eslint.config.js, src/blocks/blockESLint.test.ts, src/blocks/blockESLint.ts
Remove the explicit setting of [`tsconfigRootDir`](https://typescript-eslint.io/packages/parser/#tsconfigrootdir). Since the corresponding PR in typescript-eslint is now in review, I think it's "soon enough" to make this change in userland. Setting it explicitly is a safety precaution for edge cases.
🎁
=> fix: switch tseslint's tsconfigRootDir to implicit
