JoshuaKGoldberg/create-typescript-app

README.md

fix: fix CI badge to be build.yml

---

README.md
package.json

Uses the description from the repository.

docs: add proper description to package.json and README.md

---

README.md
src/greet.test.ts
src/greet.ts

feat: allow greet to take a string

---

README.md

Adds a badge and contributors table section to the README.md. These should be filled out as I use the bot.

docs: add all-contributors areas to README.md

---

.releaserc.json
package.json
yarn.lock

Brings in https://github.com/semantic-release/changelog to generate a `CHANGELOG.md`.

docs: add changelog generation

---

.github/workflows/compliance.yml

chore: disable ignore-team-members in compliance action

---

.eslintrc.cjs
package.json
src/types.ts
yarn.lock

chore: add eslint-plugin-typescript-sort-keys

---

.github/workflows/prune.yml
src/types.ts

Whoops. Forgot to add this as part of #48.

chore: add missing prune.yml workflow

---

.github/workflows/package.yml
.npmpackagejsonlintrc.json
package.json
yarn.lock

https://npmpackagejsonlint.org
Explicitly marks `description` and `license` as required. Because in my packages I want them.
Doesn't make sure package.json is sorted though 🤔

chore: added npm-package-json-lint in lint:package

---

.github/workflows/release.yml

ci: disable opening an issue on the initial commit

---

.github/ISSUE_TEMPLATE/01-bug.yaml
.github/ISSUE_TEMPLATE/02-documentation.yaml
.github/ISSUE_TEMPLATE/03-feature.yaml
.github/ISSUE_TEMPLATE/04-tooling.yaml

Makes them just search for all issues, even closed ones.

docs: simpler issue searches in templates

---

.github/CONTRIBUTING.md

Explicitly calls the images _unassigned_ and changes the query.

docs: specify finding unassigned good first issues

---

.github/CONTRIBUTING.md
.markdownlintignore
package.json
pnpm-lock.yaml

Brings in https://github.com/JoshuaKGoldberg/sentences-per-line. Ignores `CODE_OF_CONDUCT.md` because it's a standard copypasta template.

chore: added sentences-per-line to markdownlint

---

script/setup.js

Creates it on the bottom of README.mds as part of setup.

docs: add notice to bottom of templated README.mds

---

src/greet.ts

This is effectively a no-op change just to check whether changelogs are being generated (#20).

feat: bind console log for performance (not really)

---

.releaserc.json

Adds a title to the changelog. Not positive this will cause headings to become `##`s.

feat: add changelogTitle to .releaserc.json

---

src/greet.test.ts
src/greet.ts
vitest.config.ts

Just adding a feat to test the release flow. Working on branch protections (#81).

feat: bind console.log always to the same value

---

README.md

Fixes #64 in that it documents the need for an `NPM_TOKEN`. 😄

docs: mentioned ACCESS_TOKEN and NPM_TOKEN in setup steps

---

script/labels.json

feat: add 'area: testing' label to setup data

---

README.md

Describes what Renovate does, and lists it at the end of setup. Putting it at the end of setup is good because we don't want automerged PRs created until _after_ the setup configures branch protections & required status checks.

docs: mention Renovate installation

---

README.md

Also mentions pr-compliance-action now that we're on the topic. 😄

docs: mention allcontributors and pr-compliance-action in README.md

---

.all-contributorsrc

fix: don't skipCi for allcontributors

---

README.md

Since this template uses GitHub Actions, there shouldn't be more setup than just enabling the app on a repo.

docs: mention Codecov GitHub App in Setup

---

.prettierignore

Add coverage directory to .prettierignore file since it isnt checked into the repo and doesn't need to be formatted.

fix: add coverage directory to .prettierignore

---

.github/workflows/release.yml

Add a `write` permission to the release workflow to enable push changes and update the github token env to use the default one `github.token`
Co-authored-by: @RebeccaStevens

ci: fix release workflow permissions

---

.github/workflows/compliance.yml

Follows the package readme. Thanks @mtfoley!

fix: add permissions to compliance.yml

---

README.md

As worked on in the stream today!

docs: describe the setup script more in README.md

---

README.md
package.json

docs: updated description

---

.eslintrc.cjs
.github/ISSUE_TEMPLATE/01-bug.yml
.github/ISSUE_TEMPLATE/02-documentation.yml
.github/ISSUE_TEMPLATE/03-feature.yml
.github/ISSUE_TEMPLATE/04-tooling.yml
.github/actions/prepare/action.yml
.github/workflows/build.yml
.github/workflows/knip.yml
.github/workflows/lint.yml
.github/workflows/markdown.yml
.github/workflows/package.yml
.github/workflows/packages.yml
.github/workflows/prettier.yml
.github/workflows/setup.yml
.github/workflows/spelling.yml
.github/workflows/test.yml

- Extended yaml linter configuration with new rules to further improve consistency
- Fixed newly reported errors

chore: update yaml lint config

---

.github/workflows/release.yml
package.json

Added the changes from https://github.com/JoshuaKGoldberg/ts-api-utils/pull/91

fix(release): limit concurrency to run release one by one

---

package.json
pnpm-lock.yaml

Updated Knip to next major version (still in alpha).
Description: https://github.com/webpro/knip/issues/73
New docs: https://github.com/webpro/knip/blob/v2/README.md
Managed to run a few quick checks:

chore: update knip to new major version

---

.vscode/settings.json

Added `eslint.probe` to settings.json file with all the default formats alongside including .json and .jsonc.

fix: add ESLint Probe for default files as well as JSON and JSONC

---

package.json
pnpm-lock.yaml
script/setup-test-e2e.js
script/setup.js

Uses `npm whoami` and [`npm-user`](https://github.com/sindresorhus/npm-user) to try to retrieve data on the currently logged in npm user.
Bolsters the end-to-end testing too!

feat: populate package.json author from npm info

---

cspell.json
script/setup-test-e2e.js
script/setup.js

This PR is still big but no changes to any of the actual logic or addition of any external packages.
Only includes fancy changes involving clack spinner & try catch handling to support that.

feat(setup): ✨ add fancy clack prompt with spinner support

---

.github/CONTRIBUTING.md

Further splits up the PR docs.

docs: mention status checks

---

knip.jsonc
package.json
pnpm-lock.yaml
script/setup-test-e2e.js
script/setup.js

Added [`globby`](https://github.com/sindresorhus/globby) package. Reason - https://github.com/sindresorhus/execa/issues/555#issuecomment-1501543612

fix(setup-test): remove shell true

---

.github/CONTRIBUTING.md

Brings in the latest-and-greatest https://github.com/typescript-eslint/typescript-eslint/issues/6492 (i.e. https://github.com/typescript-eslint/typescript-eslint/issues/6492).

docs: explain PR comment/re-review more explicitly

---

script/setup.js

Missed in the `execa` conversion (#349), and not tested because it involves directly using the GitHub API.

fix: use auth.stdout, not .toString(), in setup

---

.github/renovate.json

Per https://docs.renovatebot.com/configuration-options/#postupdateoptions.

fix: add postUpdateOptions pnpmDedupe to renovate.json

---

script/labels.json

Add ":(" to the end of type: bug label description to make it more interesting

feat: add ":(" to the end of type: bug label description

---

.github/workflows/release.yml
.release-it.json

Adds support for provenance info on releases, see: https://www.npmjs.com/package/@sdl-codegen/node

feat: add provenance for releases on npm

---

package.json

Added the following property to package.json
"publishConfig": {
"provenance": true
},
This will indicate for published npm packages to use [package provenance](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/465), which is a new and important security practice.

fix: add publishConfig to package.json

---

src/setup/steps/hydrateRepositoryLabels.ts

fix: corrected labels.json import path

---

src/setup/steps/removeSetupScripts.ts

Uses `force: true, recursive: true` on all the paths.

fix: made removing setup scripts safer

---

.github/SECURITY.md
src/hydrate/steps/writing/creation/dotGitHub/rootFiles.ts

Adds a very basic security policy based on https://github.com/typescript-eslint/typescript-eslint/blob/a91bb9e264544fc635a44468c2543b94fa83ac1c/.github/SECURITY.md.

docs: added a basic security policy

---

.github/workflows/hydrate.yml
.github/workflows/setup.yml
.github/workflows/test.yml

Adds `flags: ...` to each of the three test workflows.

feat: add codecov-action flags

---

codecov.yml
src/hydrate/steps/clearUnnecessaryFiles.ts

Adds a [`codecov.yml` config file](https://docs.codecov.com/docs/codecov-yaml) with settings from https://docs.codecov.com/docs/notifications#preventing-notifications-until-after-n-builds.

build: add codecov.yml

---

.github/workflows/release.yml
src/hydrate/steps/writing/creation/dotGitHub/workflows.ts

I switched `cancel-in-progress: false` to `true` in the 2 relevant files.

fix: set cancel-in-progress: true

---

src/hydrate/values/getHydrationDefaults.ts
src/hydrate/values/readAuthorIfExists.test.ts
src/hydrate/values/readAuthorIfExists.ts
src/hydrate/values/readFundingIfExists.test.ts
src/hydrate/values/readFundingIfExists.ts
src/hydrate/values/readOwnerFromGitRemote.test.ts
src/hydrate/values/readOwnerFromGitRemote.ts

An ongoing PR for adding unit tests to hydrate components.
currently added:
- `src/hydrate/values/readAuthorIfExists`
- `src/hydrate/values/readOwnerFromGitRemote`
- `src/hydrate/values/readFundingIfExists`

test: add unit tests to hydrate/values

---

.all-contributorsrc
README.md

Touches up some of the alt text too.

docs: add emojis to README.md badges

---

.github/CONTRIBUTING.md
src/hydrate/steps/writing/creation/dotGitHub/rootFiles.ts

Per the issue, asks for a favorite emoji.

docs: mention favorite emoji at bottom of CONTRIBUTING.md

---

.github/workflows/hydrate.yml
.github/workflows/setup.yml
.github/workflows/test.yml

fix: always upload codecov results in GHA workflows

---

README.md
package.json
pnpm-lock.yaml
script/hydrate-test-e2e.js
src/hydrate/index.ts
src/hydrate/steps/detectExistingContributors.ts
src/hydrate/steps/finalizeDependencies.ts
src/hydrate/values/hydrationInputValues.ts
src/setup/steps/uninstallPackages.ts

Adds detecting existing contributors with [`all-contributors-for-repository`](https://github.com/JoshuaKGoldberg/all-contributors-for-repository), along with a `--skip-contributors` flag to skip that.

feat: fill in existing contributors in hydration

---

.github/DEVELOPMENT.md
.github/workflows/tsc.yml
README.md
cspell.json
package.json
pnpm-lock.yaml
src/hydrate/steps/writing/creation/dotGitHub/workflows.ts
tsup.config.ts

Bumps to the latest version of `tsup` to include https://github.com/egoist/tsup/pull/934.
Adds an `entry` for all non-`test` files in `src/` so that the existing directory structure is maintained.

feat: use tsup to build lib/

---

script/create-test-e2e.js
script/initialize-test-e2e.js
script/migrate-test-e2e.js
src/shared/getGitHubUserAsAllContributor.ts
tsup.config.ts

Yeah, tsup needed to enable sourcemaps.
See also the `c8` docs: https://github.com/bcoe/c8#checking-for-full-source-coverage-using---all

fix: re-enable sourcemaps and fix internal test coverage merging

---

package.json
pnpm-lock.yaml
src/steps/addToolAllContributors.test.ts
src/steps/addToolAllContributors.ts
src/steps/detectExistingContributors.test.ts
src/steps/detectExistingContributors.ts
src/steps/updateAllContributorsTable.ts

fix: always npx -y all-contributors-cli

---

.github/ISSUE_TEMPLATE/01-bug.yml
.github/ISSUE_TEMPLATE/03-feature.yml
src/steps/writing/creation/dotGitHub/issueTemplate.ts

simplified issue template titles

feat: simplified issue template titles

---

src/steps/writing/creation/dotGitHub/createDevelopment.test.ts
src/steps/writing/creation/dotGitHub/createDevelopment.ts

fix: correct createDevelopment linter lines logic

---

src/steps/writing/creation/rootFiles.ts

Keeps them in this repo because it needs them.

fix: remove asterisk from coverage templates

---

src/steps/writing/creation/dotGitHub/createDevelopment.test.ts
src/steps/writing/creation/dotGitHub/createDevelopment.ts

fix: include Type Checking section in DEVELOPMENT.md

---

src/migrate/migrateWithOptions.ts
src/steps/detectExistingContributors.test.ts
src/steps/detectExistingContributors.ts

It was fine on `JoshuaKGoldberg/create-typescript-app` 😄 just ... no other repos.

fix: pass options to contributors lookup

---

src/steps/writeReadme.test.ts
src/steps/writeReadme.ts

Also expands testing to include `funding`.

fix: adjust README.md badge indentation

---

.github/workflows/lint-package-json.yml
.github/workflows/release.yml
src/steps/initializeGitHubRepository/initializeBranchProtectionSettings.ts
src/steps/writing/creation/dotGitHub/workflows.ts

fix: update branch protection settings for lint_package-json

---

src/bin/mode.ts

fix: correct value phrasing for mode parsing

---

src/steps/writing/creation/writePackageJson.ts

This PR is responsible for adding the  `pnpm-deduplicate` package to `devDependenciesToRemove` array

feat: add pnpm-deduplicate to devDependenciesToRemove arr

---

.github/DEVELOPMENT.md

Mentions the steps I found necessary in `.github/DEVELOPMENT.md`.

docs: mention end-to-end test debugging for migration scripts

---

.prettierignore
src/steps/writing/creation/rootFiles.ts

😢. #806 was perfect. But the tooling appears to not be working properly. 
fyi @conrmahr - maybe we can try again in a few months?

fix: add .allcontributorsrc back to .prettierignore

---

src/steps/writing/creation/rootFiles.ts
tsconfig.json

Updates the repo's `tsconfig.json` file and backing template.

feat: enable noEmit in tsconfig.json

---

src/steps/writing/creation/dotGitHub/createWorkflows.test.ts
src/steps/writing/creation/dotGitHub/createWorkflows.ts

fix: invert test.yml excludes logic

---

src/shared/cli/spinners.ts

Moves the recovery pieces of the `withSpinners` loop into a `finally` so they always get called.

fix: graceful recovery for failed spinner step

---

src/steps/clearUnnecessaryFiles.ts

Adds `.eslintrc` to the list of files deleted by `clearUnnecessaryFiles.ts`

feat: Add .eslintrc to clearUnnecessaryFiles.ts

---

src/steps/writing/creation/writePackageJson.test.ts
src/steps/writing/creation/writePackageJson.ts

Removes all references to `--report-unused-disable-directives`

chore: cleanup --report-unused-disable-directives

---

script/migrate-test-e2e.js

Adds the corresponding `--bin` to migration.

chore: add --bin to migrate-test-e2e.js

---

package.json
script/__snapshots__/migrate-test-e2e.js.snap

fix: correct initialize script path

---

src/steps/writing/creation/dotGitHub/createDevelopment.test.ts
src/steps/writing/creation/dotGitHub/createDevelopment.ts

One char PRs a speciality :wink: https://github.com/oven-sh/bun/pull/2175

fix: markdown typo - the case of the extra ')'

---

knip.jsonc
package.json
pnpm-lock.yaml
script/__snapshots__/migrate-test-e2e.js.snap

Bumps Knip and removes the now-unnecessary ignore.

chore: bump Knip to 3.10.0

---

.prettierrc.json
docs/FAQs.md
src/steps/writing/creation/rootFiles.ts

Renames the file, removes one of its overrides, and updates templates.

feat: rename .prettierrc to .prettierrc.json

---

.github/workflows/contributors.yml
src/steps/writing/creation/dotGitHub/createWorkflows.test.ts
src/steps/writing/creation/dotGitHub/createWorkflows.ts

chore: bump all-contributors-auto-action to v0.4.2

---

.github/actions/prepare/action.yml
src/steps/writing/creation/dotGitHub/actions.test.ts
src/steps/writing/creation/dotGitHub/actions.ts

Swaps the number from 18 to 20. Straightforward.

feat: bump CI version of Node to 20

---

docs/FAQs.md
docs/Options.md
docs/Tooling.md
src/bin/help.test.ts
src/create/createRerunSuggestion.test.ts
src/shared/options/args.ts
src/shared/options/augmentOptionsWithExcludes.test.ts
src/shared/options/augmentOptionsWithExcludes.ts
src/shared/options/exclusionKeys.ts
src/shared/options/getBase.test.ts
src/shared/options/getBase.ts
src/shared/options/optionsSchema.ts
src/shared/options/readOptions.test.ts
src/shared/types.ts
src/steps/writing/creation/writePackageJson.test.ts
src/steps/writing/creation/writePackageJson.ts

Renames the _"minimum"_ to _**"minimal"**_ to reflect that yiou actually can get _less_ than what's in it now.

feat: add --exclude-build option

---

src/steps/finalizeDependencies.test.ts
src/steps/finalizeDependencies.ts

Adds it in as a `devDependency`.
💖

fix: also install @types/node in created projects

---

.github/renovate.json
docs/Tooling.md
src/steps/writing/creation/dotGitHub/createDotGitHubFiles.test.ts
src/steps/writing/creation/dotGitHub/createDotGitHubFiles.ts

feat: bump Renovate wait up to 7 days

---

src/steps/clearUnnecessaryFiles.ts
src/steps/writing/creation/writePackageJson.ts

Cleans up existing files and file properties related to them.
💖

feat: clear more Mocha and Jest remnants

---

src/create/createWithOptions.test.ts
src/create/createWithOptions.ts
src/initialize/initializeWithOptions.ts
src/migrate/migrateWithOptions.ts
src/shared/createCleanupCommands.test.ts
src/shared/createCleanupCommands.ts
src/steps/clearLocalGitTags.ts

At the end of `createWithOptions`, prepends a nice little Git command before the other commands. Includes a small refactor of `createCleanupCommands` to not care about the mode.
💖

fix: delete any existing Git tags in --mode create

---

src/migrate/index.test.ts
src/migrate/migrateWithOptions.test.ts

As the issue suggested, this was a fair bit of setup. But I feel better now.
💖

test: finish unit testing migrate and migrateWithOptions

---

.github/workflows/post-release.yml
src/steps/writing/creation/dotGitHub/createWorkflows.test.ts
src/steps/writing/creation/dotGitHub/createWorkflows.ts

fix: reset post-release back to npm pkg get again

---

docs/Options.md

Just a simple typo fix in the docs :)

docs: fixing small typo around initialize

---

cspell.json
script/__snapshots__/migrate-test-e2e.ts.snap
src/steps/writing/creation/rootFiles.ts

 fix: ignore .all-contributorsrc in cspell.json

---

eslint.config.js
script/__snapshots__/migrate-test-e2e.ts.snap

I'd left in this bit by accident.
💖

fix: finish removing **/*.md/*.ts eslint.config.js overrides

---

.github/workflows/ci.yml
script/__snapshots__/migrate-test-e2e.ts.snap

Straightforward find-and-replace.
💖

chore: switch Are The Types Wrong job to Title Case

---

.github/actions/prepare/action.yml
.github/workflows/accessibility-alt-text-bot.yml
.github/workflows/ci.yml
.github/workflows/contributors.yml
.github/workflows/post-release.yml
.github/workflows/pr-review-requested.yml
.github/workflows/release.yml
.github/workflows/test-create.yml
.github/workflows/test-initialize.yml
.github/workflows/test-migrate.yml

Reverts JoshuaKGoldberg/create-typescript-app#1731

Revert "chore(deps): pin dependencies"

---

.github/actions/prepare/action.yml
.github/renovate.json
.github/workflows/accessibility-alt-text-bot.yml
.github/workflows/ci.yml
.github/workflows/contributors.yml
.github/workflows/post-release.yml
.github/workflows/pr-review-requested.yml
.github/workflows/release.yml
script/__snapshots__/migrate-test-e2e.ts.snap

I don't want these to update at all.
💖

chore: disable Renovate on GitHub Actions internally

---

cspell.json

chore: removed unnecessary cspell.json words

---

docs/Options.md

Mentions `--auto` at the bottom of `Options.md` as described.
Touches up wording to say "offline _manner_" - since _"mode"_ refers to `--mode`.
💖

docs: mentioned --auto Automatic Mode

---

package.json
pnpm-lock.yaml
src/next/blocks/blockPackageJson.test.ts
src/next/blocks/blockPackageJson.ts
src/steps/uninstallPackages.ts
src/steps/writing/creation/index.test.ts

Uses the convenient [`remove-undefined-objects`](https://www.npmjs.com/package/remove-undefined-objects).
💖

chore: remove empty properties in blockPackageJson

---

.github/workflows/ci.yml
script/__snapshots__/migrate-test-e2e.ts.snap

chore: run with --version in CI

---

src/steps/updateReadme.test.ts
src/steps/updateReadme.ts

fix: remove project logo in initialization

---

.all-contributorsrc
.prettierignore
script/__snapshots__/migrate-test-e2e.ts.snap
src/next/blocks/blockAllContributors.test.ts
src/next/blocks/blockAllContributors.ts
src/steps/writing/creation/rootFiles.ts

Also fixes a `doc`/`docs` typo while I'm in the area.
💖

fix: remove .all-contributorsrc from .prettierignore

---

README.md
package.json
script/__snapshots__/migrate-test-e2e.ts.snap
src/shared/options/createOptionDefaults/readDefaultsFromReadme.test.ts

docs: switch emoji to 🎁

---

src/steps/writing/creation/dotGitHub/createJobName.ts
src/steps/writing/creation/dotGitHub/createMultiWorkflowFile.ts
src/steps/writing/creation/dotGitHub/createSoloWorkflowFile.ts

Extracts to a shared helper since there are two places this is relevant.
💖

fix: remove question marks from GHA job names

---

src/next/blocks/blockTSup.ts

feat: add runArgs to blockTSup

---

knip.json
script/__snapshots__/migrate-test-e2e.ts.snap
src/next/blocks/blockKnip.ts
src/steps/writing/creation/createKnipConfig.test.ts
src/steps/writing/creation/createKnipConfig.ts

fix: don't include ! in Knip files

---

script/__snapshots__/migrate-test-e2e.ts.snap
src/next/blocks/blockESLintNode.test.ts
src/next/blocks/blockESLintNode.ts

feat: don't add n/no-missing-import if usage doesn't need it

---

src/next/blocks/blockKnip.test.ts
src/next/blocks/blockKnip.ts

feat: add addons.ignoreDependencies to blockKnip

---

src/next/blocks/blockESLint.test.ts
src/next/blocks/blockESLint.ts

feat: add addons.explanations to blockESLint

---

src/next/blocks/blockCodecov.test.ts
src/next/blocks/blockCodecov.ts
src/next/blocks/blockGitHubActionsCI.ts
src/next/blocks/blockVitest.test.ts
src/next/blocks/blockVitest.ts
src/next/presets/presetCommon.ts

Also removes `addons.flags` from `blockVitest` since this repo won't use them after #1839.
💖

feat: extract codecov uploading to a blockCodecov

---

src/next/blocks/blockPrettier.test.ts
src/next/blocks/blockPrettier.ts

fix: correct blockPrettier .husky/pre-commit mode to 33279 / -rwxrwxrwx

---

src/next/blocks/blockCodecov.test.ts
src/next/blocks/blockCodecov.ts
src/next/blocks/blockContributingDocs.test.ts
src/next/blocks/blockContributingDocs.ts
src/next/blocks/blockContributorCovenant.test.ts
src/next/blocks/blockContributorCovenant.ts
src/next/blocks/blockDevelopmentDocs.test.ts
src/next/blocks/blockDevelopmentDocs.ts
src/next/blocks/blockESLint.ts
src/next/blocks/blockGitHubActionsCI.test.ts
src/next/blocks/blockGitHubActionsCI.ts
src/next/blocks/blockKnip.ts
src/next/blocks/blockPackageJson.ts
src/next/blocks/blockPrettier.ts
src/next/blocks/blockTSup.test.ts
src/next/blocks/blockTSup.ts
src/next/blocks/blockVitest.test.ts
src/next/blocks/blockVitest.ts

Corresponding to https://github.com/JoshuaKGoldberg/create/pull/137.
💖

fix: run migration rm scripts with silent: true

---

src/next/blocks/blockPackageJson.test.ts
src/next/blocks/blockPackageJson.ts

fix: correct --offline ternary in blockPackageJson

---

src/base.ts
src/options/readAccess.test.ts
src/options/readAccess.ts
src/types.ts

feat: infer access option from package.json

---

.prettierignore
src/blocks/blockAllContributors.test.ts
src/blocks/blockAllContributors.ts
src/blocks/blockCTATransitions.test.ts

fix: add /.all-contributorsrc back to .prettierignore again

---

src/blocks/blockPnpmDedupe.test.ts
src/blocks/blockPnpmDedupe.ts

Added a snapshot test while I was in the area.
💖

fix: run pnpm dedupe without --offline

---

src/blocks/blockPackageJson.test.ts
src/blocks/blockPackageJson.ts

fix: run pnpm install with --no-frozen-lockfile

---

src/blocks/blockTemplatedWith.test.ts
src/blocks/blockTemplatedWith.ts

feat: hide 'no worries' notice when I am the owner

---

src/blocks/blockCTATransitions.test.ts
src/blocks/blockCTATransitions.ts

fix: use npx in transition action

---

README.md
src/blocks/blockAllContributors.test.ts
src/blocks/blockAllContributors.ts
src/blocks/blockCodecov.test.ts
src/blocks/blockCodecov.ts
src/blocks/blockContributorCovenant.test.ts
src/blocks/blockContributorCovenant.ts
src/blocks/blockMITLicense.ts
src/blocks/blockREADME.test.ts
src/blocks/blockREADME.ts
src/blocks/blockReleaseIt.ts

Caught a couple of discrepancies in how the README.md badges are printed. Nice.
🎁

fix: provide README badges via addons

---

docs/Blocks.md
src/docsBlocks.test.ts

Throws in a nice little example for good measure.
🎁

docs: also mention --add-* CLI flags

---

src/blocks/blockReleaseIt.test.ts
src/blocks/blockReleaseIt.ts
src/blocks/blockTSup.test.ts
src/blocks/blockTSup.ts

feat: allow customizing release.yml build steps

---

src/blocks/blockCTATransitions.ts

fix: pin actions versions in cta-transitions.yml

---

src/blocks/blockVitest.test.ts
src/blocks/blockVitest.ts

feat: add flags Addon to blockVitest

---

package.json
pnpm-lock.yaml

Pulling these in manually to get:
* https://github.com/JoshuaKGoldberg/bingo/pull/301
* https://github.com/JoshuaKGoldberg/bingo/pull/328
💝

fix(deps): bingo@ 0.5.11, bingo-stratum@0.5.8

---

package.json
pnpm-lock.yaml
src/blocks/blockCodecov.test.ts
src/blocks/blockCodecov.ts
src/blocks/intake/intakeFile.test.ts
src/blocks/intake/intakeFile.ts
src/blocks/intake/intakeFileAsYaml.test.ts
src/blocks/intake/intakeFileAsYaml.ts

Attempts to load an existing `ci.yml` as JSON and find the Codecov step. If that step exists and has an `env`, hooray!
🎁

feat: add intake method to blockCodecov

---

src/options/readReadmeAdditional.test.ts
src/options/readReadmeAdditional.ts

fix: detect additional content after ALL-CONTRIBUTORS-LIST:END

---

src/blocks/blockTypeScript.test.ts
src/blocks/blockTypeScript.ts

fix: sort compilerOptions in tsconfig.json

---

src/blocks/blockPackageJson.test.ts
src/blocks/blockPackageJson.ts

fix: handle subset file matches in blockPackageJson

---

src/blocks/blockReleaseIt.test.ts
src/blocks/blockReleaseIt.ts

fix: bump release-it-action to 0.3.1

---

src/blocks/blockPrettier.test.ts
src/blocks/blockPrettier.ts

fix: add runBefore to local CLI run in blockPrettier

---

src/base.ts
src/blocks/blockREADME.test.ts
src/blocks/blockREADME.ts
src/options/readDocumentation.ts
src/options/readReadmeAdditional.ts
src/options/readReadmeFootnotes.test.ts
src/options/readReadmeFootnotes.ts
src/schemas.ts

fix: account for footnotes in README.md

---

src/base.ts
src/blocks/blockVitest.test.ts
src/blocks/blockVitest.ts

feat: added blockVitest environment and flags intake

---

src/blocks/blockTypeScript.test.ts
src/blocks/blockTypeScript.ts

feat: add intake to blockTypeScript

---

src/blocks/blockCSpell.test.ts
src/blocks/blockCSpell.ts

feat: add intake to blockCspell

---

README.md

docs: remove 'early stage' from README.md note

---

src/blocks/blockESLintPlugin.test.ts
src/blocks/blockESLintPlugin.ts

feat: add build --no-dts before eslint-doc-generator in blockESLintPlugin build:docs

---

src/blocks/blockGitHubActionsCI.test.ts
src/blocks/blockGitHubActionsCI.ts

Includes an `intake` method so it can be inferred from disk.
🎁

feat: added nodeVersion Addon to blockGitHubActionsCI

---

src/blocks/blockTemplatedWith.test.ts
src/blocks/blockTemplatedWith.ts

fix: refer to Bingo as a framework, not an engine

---

.all-contributorsrc
src/blocks/blockAllContributors.test.ts
src/blocks/blockAllContributors.ts

fix: put redundant .all-contributorsrc properties back

---

eslint.config.js
src/blocks/blockESLintYML.test.ts
src/blocks/blockESLintYML.ts

Swaps over as described by the issue. 
🎁

feat: use eslint-plugin-yml's 'standard' config
